# generated by datamodel-codegen:
#   filename:  techdoc.json
#   timestamp: 2026-08-08T10:11:01+00:00

from __future__ import annotations

from datetime import datetime as datetime_aliased
from enum import StrEnum
from typing import Any, Literal

from pydantic import BaseModel, Field, constr


class AnalyticsRequestModel(BaseModel):
    product_history_ids: list[str] | None = Field(None, title='Product History Ids')
    kt_ids: list[str] | None = Field(None, title='Kt Ids')
    product_family_history_ids: list[str] | None = Field(
        None, title='Product Family History Ids'
    )


class BulkKnowledgeTopicFetchRequest(BaseModel):
    knowledge_topic_ids: list[str] | None = Field(None, title='Knowledge Topic Ids')
    include_use_case_config: bool | None = Field(False, title='Include Use Case Config')


class BulkKnowledgeUnitFetchItem(BaseModel):
    history_id: str = Field(
        ..., examples=['5eb7cf5a86d9755df3a6c593'], title='History Id'
    )
    version: str | None = Field(None, title='Version')
    latest_approved: bool | None = Field(False, title='Latest Approved')


class BulkKnowledgeUnitFetchRequest(BaseModel):
    items: list[BulkKnowledgeUnitFetchItem] | None = Field(
        None, max_length=500, title='Items'
    )


class BulkProductFamilyFetchItem(BaseModel):
    history_id: str = Field(
        ..., examples=['5eb7cf5a86d9755df3a6c593'], title='History Id'
    )
    version: str | None = Field(None, title='Version')
    latest_approved: bool | None = Field(False, title='Latest Approved')


class BulkProductFamilyFetchRequest(BaseModel):
    items: list[BulkProductFamilyFetchItem] | None = Field(
        None, max_length=500, title='Items'
    )


class BulkProductFetchItem(BaseModel):
    history_id: str = Field(
        ..., examples=['5eb7cf5a86d9755df3a6c593'], title='History Id'
    )
    version: str | None = Field(None, title='Version')
    latest_approved: bool | None = Field(False, title='Latest Approved')
    combine_related_product_families_kus: bool | None = Field(
        False, title='Combine Related Product Families Kus'
    )


class BulkProductFetchRequest(BaseModel):
    items: list[BulkProductFetchItem] | None = Field(
        None, max_length=500, title='Items'
    )


class CommitKnowledgeUnitRevisionRequest(BaseModel):
    commit_message: str = Field(..., title='Commit Message')


class CommitKnowledgeUnitSchemaRevisionRequest(BaseModel):
    commit_message: str = Field(..., title='Commit Message')


class CommitProductFamilyRevisionRequest(BaseModel):
    commit_message: str = Field(..., title='Commit Message')


class CommitProductRevisionRequest(BaseModel):
    commit_message: str = Field(..., title='Commit Message')


class ConditionalFieldStatus(StrEnum):
    present = 'present'
    missing = 'missing'
    hidden = 'hidden'


class CreateKUSchemaLibraryBase(BaseModel):
    name: str = Field(..., title='Name')
    description: str | None = Field(None, title='Description')
    knowledge_unit_schema_ids: list[str] | None = Field(
        [], title='Knowledge Unit Schema Ids'
    )


class CreateKnowledgeTopicFromExisting(BaseModel):
    kt_schema_id: str | None = Field(
        None,
        description='ID of existing knowledge topic schema to copy from',
        title='Kt Schema Id',
    )
    kt_id: str | None = Field(
        None, description='ID of knowledge topic to create schema from', title='Kt Id'
    )
    include_content: bool | None = Field(
        False,
        description='Whether to include content in the copy',
        title='Include Content',
    )


class CreateKnowledgeTopicSchemaFromExisting(BaseModel):
    kt_schema_id: str | None = Field(
        None,
        description='ID of existing knowledge topic schema to copy from',
        title='Kt Schema Id',
    )
    kt_id: str | None = Field(
        None, description='ID of knowledge topic to create schema from', title='Kt Id'
    )
    include_content: bool | None = Field(
        False,
        description='Whether to include content in the copy',
        title='Include Content',
    )


class CreateKnowledgeTopicSchemasFromExisting(BaseModel):
    kt_schema_ids: list[str] | None = Field(
        None,
        description='ID of existing knowledge topic schema to copy from',
        title='Kt Schema Ids',
    )
    kt_ids: list[str] | None = Field(
        None, description='ID of knowledge topic to create schema from', title='Kt Ids'
    )
    include_content: bool | None = Field(
        False,
        description='Whether to include content in the copy',
        title='Include Content',
    )
    knowledge_unit_schema_history_id: str | None = Field(
        '',
        description='knowledge unit id to add the knowledge topics',
        title='Knowledge Unit Schema History Id',
    )


class CreateKnowledgeUnitSchemaBase(BaseModel):
    knowledge_unit_name: str = Field(..., title='Knowledge Unit Name')
    knowledge_unit_description: str | None = Field(
        None, title='Knowledge Unit Description'
    )
    knowledge_topic_schemas: list[str] | None = Field(
        [], title='Knowledge Topic Schemas'
    )
    is_not_editable_for_children: bool | None = Field(
        False, title='Is Not Editable For Children'
    )
    library_ids: list[str] | None = Field([], title='Library Ids')


class CreateKnowledgeUnitSchemaFromExisting(BaseModel):
    ku_schema_id: str | None = Field(
        None,
        description='ID of existing knowledge unit schema to copy from',
        title='Ku Schema Id',
    )
    ku_id: str | None = Field(
        None, description='ID of knowledge unit to create schema from', title='Ku Id'
    )
    include_content: bool | None = Field(
        False,
        description='Whether to include content in the copy',
        title='Include Content',
    )


class CreateKnowledgeUnitSchemasFromExisting(BaseModel):
    ku_schema_ids: list[str] | None = Field(None, title='Ku Schema Ids')
    ku_ids: list[str] | None = Field(None, title='Ku Ids')
    include_content: bool | None = Field(False, title='Include Content')
    library_ids: list[str] | None = Field(None, title='Library Ids')


class DeleteLibraryMode(StrEnum):
    unlink_schemas = 'unlink_schemas'
    delete_all = 'delete_all'


class DuplicateKnowledgeTopic(BaseModel):
    kt_schema_id: str | None = Field(
        None,
        description='ID of existing knowledge topic schema to copy from',
        title='Kt Schema Id',
    )
    kt_id: str | None = Field(
        None, description='ID of knowledge topic to create schema from', title='Kt Id'
    )
    include_content: bool | None = Field(
        False,
        description='Whether to include content in the copy',
        title='Include Content',
    )


class DuplicateKnowledgeTopicSchema(BaseModel):
    kt_schema_id: str | None = Field(
        None,
        description='ID of existing knowledge topic schema to copy from',
        title='Kt Schema Id',
    )
    kt_id: str | None = Field(
        None, description='ID of knowledge topic to create schema from', title='Kt Id'
    )
    include_content: bool | None = Field(
        False,
        description='Whether to include content in the copy',
        title='Include Content',
    )


class DuplicateProduct(BaseModel):
    product_history_id: str = Field(..., title='Product History Id')
    include_content: bool = Field(..., title='Include Content')
    version: str | None = Field(None, title='Version')


class ExportUnitsRequest(BaseModel):
    unit_history_ids: list[str] = Field(
        ..., description='List of unit/schema IDs to export', title='Unit History Ids'
    )
    version: str | None = Field(
        None,
        description="Version string (e.g. '2.1') to export only that specific revision",
        title='Version',
    )


class ExternalSourceInfo(BaseModel):
    is_external: Literal['true'] = Field(..., title='Is External')
    external_source_type: str = Field(..., title='External Source Type')
    external_source_id: str = Field(..., title='External Source Id')
    metadata: dict[str, Any] | None = Field(None, title='Metadata')


class GetKnowledgeUnitSchemaHistoryGroupsRequest(BaseModel):
    knowledge_unit_schema_revision_ids: list[str] = Field(
        ...,
        description='List of knowledge unit schema revision IDs',
        title='Knowledge Unit Schema Revision Ids',
    )


class GuidanceTaskResponse(BaseModel):
    id: str = Field(..., title='Id')
    label: str = Field(..., title='Label')


class GuidanceTaskState(StrEnum):
    open = 'open'
    done = 'done'
    na = 'na'


class ImportRequest(BaseModel):
    files: list[str] = Field(
        ..., description='JSON files in string format to import', title='Files'
    )
    library_ids: list[str] | None = Field(
        None,
        description='Library IDs to associate with imported schemas',
        title='Library Ids',
    )


class ImportRequestWithProductAndFamily(BaseModel):
    files: list[str] = Field(
        ..., description='JSON files in string format to import', title='Files'
    )
    product_history_id: str | None = Field(
        None,
        description='ID of product history to associate with imported schemas',
        title='Product History Id',
    )
    family_id: str | None = Field(
        None,
        description='ID of product family to associate with imported schemas',
        title='Family Id',
    )


class ImportResponse(BaseModel):
    successful_imports: int | None = Field(
        0,
        description='Number of successfully imported units',
        title='Successful Imports',
    )
    failed_imports: int | None = Field(
        0, description='Number of failed imports', title='Failed Imports'
    )
    error_details: list[dict[str, Any]] | None = Field(
        None, description='Details of any failed imports', title='Error Details'
    )


class InputType(StrEnum):
    textfield = 'textfield'
    textarea = 'textarea'
    number = 'number'
    select = 'select'
    checkbox = 'checkbox'
    checklist = 'checklist'
    radio = 'radio'
    date = 'date'
    datetime = 'datetime'
    time = 'time'
    taglist = 'taglist'


class IssuingEntityTypeEnum(StrEnum):
    EUDAMED = 'EUDAMED'
    GS1 = 'GS1'
    IFA = 'IFA'
    HIBCC = 'HIBCC'
    ICCBBA = 'ICCBBA'


class JiraTokenRequest(BaseModel):
    code: str = Field(..., title='Code')
    code_verifier: str = Field(..., title='Code Verifier')


class JiraTokenResponse(BaseModel):
    access_token: str = Field(..., title='Access Token')
    expires_in: int = Field(..., title='Expires In')


class KUStatistics(BaseModel):
    ku_name: str = Field(..., title='Ku Name')
    ku_history_id: str = Field(..., title='Ku History Id')
    ku_current_version: str = Field(..., title='Ku Current Version')
    ku_has_approved: bool = Field(..., title='Ku Has Approved')
    ku_is_latest_approved: bool = Field(..., title='Ku Is Latest Approved')
    ku_latest_approved_version: str = Field(..., title='Ku Latest Approved Version')


class KnowledgeTopicOrderUpdate(BaseModel):
    topic_ids: list[str] = Field(..., title='Topic Ids')
    knowledge_unit_history_id: str = Field(..., title='Knowledge Unit History Id')


class KnowledgeTopicSchemaOrderUpdate(BaseModel):
    topic_schema_ids: list[str] = Field(..., title='Topic Schema Ids')
    knowledge_unit_schema_id: str = Field(..., title='Knowledge Unit Schema Id')


class KnowledgeTopicSchemaView(BaseModel):
    id: str = Field(..., title='Id')
    knowledge_topic_name: str = Field(..., title='Knowledge Topic Name')
    knowledge_topic_schema_history_id: str = Field(
        ..., title='Knowledge Topic Schema History Id'
    )
    knowledge_unit_schema_history_id: str = Field(
        ..., title='Knowledge Unit Schema History Id'
    )
    knowledge_unit_schema_name: str = Field(..., title='Knowledge Unit Schema Name')
    knowledge_unit_schema_version: str = Field(
        ..., title='Knowledge Unit Schema Version'
    )


class KnowledgeTopicType(StrEnum):
    single_record = 'single_record'
    multi_record = 'multi_record'
    product_data_collection = 'product_data_collection'


class KnowledgeTopicUpdate(BaseModel):
    data: dict[str, Any] | None = Field(None, title='Data')
    knowledge_topic_name: str | None = Field(None, title='Knowledge Topic Name')
    knowledge_topic_schema: dict[str, Any] | None = Field(
        None, title='Knowledge Topic Schema'
    )


class KnowledgeTopicVersionEntry(BaseModel):
    kt_revision_id: str = Field(..., title='Kt Revision Id')
    kt_history_id: str = Field(..., title='Kt History Id')
    kt_name: str = Field(..., title='Kt Name')
    ku_revision_id: str = Field(..., title='Ku Revision Id')
    ku_history_id: str = Field(..., title='Ku History Id')
    ku_version: str = Field(..., title='Ku Version')
    is_approved: bool = Field(..., title='Is Approved')
    type: KnowledgeTopicType


class KnowledgeTopic1(BaseModel):
    id: str = Field(..., title='Id')
    collection: str = Field(..., title='Collection')


class KnowledgeUnitOption(BaseModel):
    knowledge_unit_history_id: str = Field(
        ...,
        description='The Knowledge Unit History ID (stable ID)',
        examples=['5eb7cf5a86d9755df3a6c593'],
        title='Knowledge Unit History Id',
    )
    current_revision_id: str = Field(
        ...,
        description='The ID of the latest revision',
        examples=['5eb7cf5a86d9755df3a6c593'],
        title='Current Revision Id',
    )
    knowledge_unit_name: str = Field(..., title='Knowledge Unit Name')
    product_name: str = Field(..., title='Product Name')
    version_string: str = Field(..., title='Version String')
    product_history_id: str = Field(
        ..., examples=['5eb7cf5a86d9755df3a6c593'], title='Product History Id'
    )
    from_family: bool = Field(..., title='From Family')


class KnowledgeUnitRevisionSlim(BaseModel):
    id: str = Field(..., examples=['5eb7cf5a86d9755df3a6c593'], title='Id')
    version_string: str = Field(..., title='Version String')
    is_latest_approved: bool = Field(..., title='Is Latest Approved')


class KnowledgeUnitRevisionSummary(BaseModel):
    id: str = Field(..., examples=['5eb7cf5a86d9755df3a6c593'], title='Id')
    name: str = Field(..., title='Name')
    version_string: str = Field(..., title='Version String')
    is_latest_approved: bool = Field(..., title='Is Latest Approved')
    read_only: bool = Field(..., title='Read Only')
    created_at: datetime_aliased = Field(..., title='Created At')
    updated_at: datetime_aliased | None = Field(None, title='Updated At')
    created_by: str = Field(..., title='Created By')
    updated_by: str | None = Field(None, title='Updated By')
    commit_message: str | None = Field(None, title='Commit Message')
    direct_approval_published_at: datetime_aliased | None = Field(
        None, title='Direct Approval Published At'
    )
    direct_approval_published_by: str | None = Field(
        None, title='Direct Approval Published By'
    )


class KnowledgeTopicSchema1(BaseModel):
    id: str = Field(..., title='Id')
    collection: str = Field(..., title='Collection')


class Library(BaseModel):
    id: str = Field(..., title='Id')
    collection: str = Field(..., title='Collection')


class KnowledgeUnitSchema1(BaseModel):
    id: str = Field(..., title='Id')
    collection: str = Field(..., title='Collection')


class KnowledgeUnitSchemaRevisionSummary(BaseModel):
    id: str = Field(..., examples=['5eb7cf5a86d9755df3a6c593'], title='Id')
    name: str = Field(..., title='Name')
    version_string: str = Field(..., title='Version String')
    is_latest_approved: bool = Field(..., title='Is Latest Approved')
    read_only: bool = Field(..., title='Read Only')
    created_at: datetime_aliased = Field(..., title='Created At')
    updated_at: datetime_aliased | None = Field(None, title='Updated At')
    created_by: str = Field(..., title='Created By')
    updated_by: str | None = Field(None, title='Updated By')
    commit_message: str | None = Field(None, title='Commit Message')


class Status(StrEnum):
    success = 'success'
    skipped_no_trace = 'skipped_no_trace'
    failed = 'failed'


class KtSyncResult(BaseModel):
    knowledge_topic_history_id: str = Field(
        ..., examples=['5eb7cf5a86d9755df3a6c593'], title='Knowledge Topic History Id'
    )
    knowledge_topic_name: str = Field(..., title='Knowledge Topic Name')
    status: Status = Field(..., title='Status')
    reason: str | None = Field(None, title='Reason')


class LastActionType(StrEnum):
    created = 'created'
    updated = 'updated'
    published = 'published'


class MissingFieldName(BaseModel):
    record_display_name: str = Field(..., title='Record Display Name')
    missing_field_name: str = Field(..., title='Missing Field Name')


class NoExternalSource(BaseModel):
    is_external: Literal['false'] = Field('false', title='Is External')


class OrderedKnowledgeTopic(BaseModel):
    knowledge_topic_id: str = Field(
        ..., examples=['5eb7cf5a86d9755df3a6c593'], title='Knowledge Topic Id'
    )
    index: int = Field(..., title='Index')


class OrderedKnowledgeTopicSchema(BaseModel):
    knowledge_topic_schema_id: str = Field(
        ..., examples=['5eb7cf5a86d9755df3a6c593'], title='Knowledge Topic Schema Id'
    )
    index: int = Field(..., title='Index')


class ParentEntity(StrEnum):
    PRODUCT = 'PRODUCT'
    PRODUCT_FAMILY = 'PRODUCT_FAMILY'


class ProductFamily(BaseModel):
    id: str = Field(..., title='Id')
    collection: str = Field(..., title='Collection')


class KnowledgeUnit1(BaseModel):
    id: str = Field(..., title='Id')
    collection: str = Field(..., title='Collection')


class ProductContextQuestion(BaseModel):
    question: str = Field(..., title='Question')
    answer: str = Field(..., title='Answer')


class ProductFamilyFields(BaseModel):
    present_fields: list[str] = Field(..., title='Present Fields')
    missing_fields: list[str] = Field(..., title='Missing Fields')
    values: dict[str, Any] = Field(..., title='Values')


class ProductFamilyRevisionSummary(BaseModel):
    id: str = Field(..., examples=['5eb7cf5a86d9755df3a6c593'], title='Id')
    name: str = Field(..., title='Name')
    version_string: str = Field(..., title='Version String')
    is_latest_approved: bool = Field(..., title='Is Latest Approved')
    read_only: bool = Field(..., title='Read Only')
    created_at: datetime_aliased = Field(..., title='Created At')
    updated_at: datetime_aliased | None = Field(None, title='Updated At')
    created_by: str = Field(..., title='Created By')
    updated_by: str | None = Field(None, title='Updated By')
    commit_message: str | None = Field(None, title='Commit Message')


class ProductFields(BaseModel):
    present_fields: list[str] = Field(..., title='Present Fields')
    missing_fields: list[str] = Field(..., title='Missing Fields')
    values: dict[str, Any] = Field(..., title='Values')
    has_product_family: bool = Field(..., title='Has Product Family')
    product_family_count: int = Field(..., title='Product Family Count')


class ProductGuidanceResponse(BaseModel):
    id: str | None = Field(None, title='Id')
    product_history_id: str = Field(
        ..., examples=['5eb7cf5a86d9755df3a6c593'], title='Product History Id'
    )
    task_states: dict[constr(pattern=r'^[a-z0-9_]+$'), GuidanceTaskState] = Field(
        ..., title='Task States'
    )


class ProductRevisionSummary(BaseModel):
    id: str = Field(..., examples=['5eb7cf5a86d9755df3a6c593'], title='Id')
    name: str = Field(..., title='Name')
    version_string: str = Field(..., title='Version String')
    is_latest_approved: bool = Field(..., title='Is Latest Approved')
    read_only: bool = Field(..., title='Read Only')
    created_at: datetime_aliased = Field(..., title='Created At')
    updated_at: datetime_aliased | None = Field(None, title='Updated At')
    created_by: str = Field(..., title='Created By')
    updated_by: str | None = Field(None, title='Updated By')
    commit_message: str | None = Field(None, title='Commit Message')
    direct_approval_published_at: datetime_aliased | None = Field(
        None, title='Direct Approval Published At'
    )
    direct_approval_published_by: str | None = Field(
        None, title='Direct Approval Published By'
    )


class PublishKnowledgeUnitRevisionRequest(BaseModel):
    commit_message: str = Field(..., title='Commit Message')


class PublishKnowledgeUnitSchemaRevisionRequest(BaseModel):
    commit_message: str = Field(..., title='Commit Message')


class PublishProductFamilyRevisionRequest(BaseModel):
    commit_message: str = Field(..., title='Commit Message')


class PublishProductRevisionRequest(BaseModel):
    commit_message: str = Field(..., title='Commit Message')


class Regulation(StrEnum):
    MDR = 'MDR'
    IVDR = 'IVDR'


class Reusable(StrEnum):
    Surgical_Reusable_Instrument = 'Surgical Reusable Instrument'
    Other = 'Other'
    Single_Use = 'Single Use'


class RiskAnalysisMatrixCell(BaseModel):
    record_id: str = Field(..., title='Record Id')
    name: str = Field(..., title='Name')
    data: dict[str, Any] | None = Field({}, title='Data')


class RiskAnalysisMatrixRow(BaseModel):
    system_misbehaviour: RiskAnalysisMatrixCell | None = None
    hazard: RiskAnalysisMatrixCell | None = None
    hazardous_situation: RiskAnalysisMatrixCell | None = None
    harm: RiskAnalysisMatrixCell | None = None
    risk: RiskAnalysisMatrixCell
    risk_control_measure: RiskAnalysisMatrixCell | None = None
    risk_management_team: RiskAnalysisMatrixCell | None = None


class RiskClass(StrEnum):
    I = 'I'
    IIa = 'IIa'
    IIb = 'IIb'
    III = 'III'
    A = 'A'
    B = 'B'
    C = 'C'
    D = 'D'


class SchemaKnowledgeTopicInput(BaseModel):
    key: str = Field(..., title='Key')
    label: str = Field(..., title='Label')
    components: list[SchemaKnowledgeTopicInput] | None = Field(None, title='Components')
    type: str | None = Field(None, title='Type')
    path: str | None = Field(None, title='Path')


class SchemaKnowledgeTopicSchema(BaseModel):
    components: list[SchemaKnowledgeTopicInput] = Field(..., title='Components')


class SearchEntityType(StrEnum):
    PRODUCT = 'PRODUCT'
    KNOWLEDGE_UNIT = 'KNOWLEDGE_UNIT'
    KNOWLEDGE_TOPIC = 'KNOWLEDGE_TOPIC'


class SearchResultItem(BaseModel):
    id: str = Field(..., examples=['5eb7cf5a86d9755df3a6c593'], title='Id')
    type: SearchEntityType
    name: str = Field(..., title='Name')
    product_history_id: str | None = Field(None, title='Product History Id')
    knowledge_unit_history_id: str | None = Field(
        None, title='Knowledge Unit History Id'
    )


class SearchResults(BaseModel):
    results: list[SearchResultItem] = Field(..., title='Results')


class SkippedKnowledgeTopic(BaseModel):
    id: str = Field(..., description='ID of the skipped knowledge topic', title='Id')
    name: str = Field(
        ..., description='Name of the skipped knowledge topic', title='Name'
    )
    reason: str = Field(
        ..., description='Reason why the knowledge topic was skipped', title='Reason'
    )


class SlimKnowledgeUnitRef(BaseModel):
    field_id: str = Field(
        ..., alias='_id', examples=['5eb7cf5a86d9755df3a6c593'], title='Id'
    )


class SlimProductFamilyRef(BaseModel):
    field_id: str = Field(
        ..., alias='_id', examples=['5eb7cf5a86d9755df3a6c593'], title='Id'
    )
    product_family_history_id: str = Field(
        ..., examples=['5eb7cf5a86d9755df3a6c593'], title='Product Family History Id'
    )
    name: str = Field(..., title='Name')


class SlimProductRef(BaseModel):
    field_id: str = Field(
        ..., alias='_id', examples=['5eb7cf5a86d9755df3a6c593'], title='Id'
    )
    product_history_id: str = Field(
        ..., examples=['5eb7cf5a86d9755df3a6c593'], title='Product History Id'
    )
    name: str = Field(..., title='Name')


class Software(StrEnum):
    NoSoftware = 'NoSoftware'
    Software_Only = 'Software Only'
    Embedded = 'Embedded'


class SoftwareClass(StrEnum):
    NoSoftware = 'NoSoftware'
    A = 'A'
    B = 'B'
    C = 'C'


class TenantMetadata(BaseModel):
    tenant_id: str = Field(..., title='Tenant Id')


class TraceInfo(BaseModel):
    source: str = Field(..., title='Source')
    target: str = Field(..., title='Target')
    relation_type: str = Field(..., title='Relation Type')


class ChangeType(StrEnum):
    update = 'update'
    new = 'new'
    remove = 'remove'


class UnderlyingSchemaSyncTopic(BaseModel):
    knowledge_topic_history_id: str = Field(
        ..., examples=['5eb7cf5a86d9755df3a6c593'], title='Knowledge Topic History Id'
    )
    knowledge_topic_name: str = Field(..., title='Knowledge Topic Name')
    change_type: ChangeType = Field(..., title='Change Type')


class UpdateGuidanceTaskStatePayload(BaseModel):
    task_id: str = Field(..., title='Task Id')
    state: GuidanceTaskState


class UpdateKUSchemaLibrary(BaseModel):
    name: str | None = Field(None, title='Name')
    description: str | None = Field(None, title='Description')
    knowledge_unit_schema_ids: list[str] | None = Field(
        [], title='Knowledge Unit Schema Ids'
    )


class UpdateKnowledgeTopicSchema(BaseModel):
    knowledge_topic_name: str | None = Field(None, title='Knowledge Topic Name')
    component_schema: dict[str, Any] | None = Field(None, title='Component Schema')
    data: dict[str, Any] | None = Field(None, title='Data')
    knowledge_unit_schema_history_id: str | None = Field(
        None, title='Knowledge Unit Schema History Id'
    )


class UpdateKnowledgeUnitSchema(BaseModel):
    knowledge_unit_name: str | None = Field(None, title='Knowledge Unit Name')
    knowledge_unit_description: str | None = Field(
        None, title='Knowledge Unit Description'
    )
    is_not_editable_for_children: bool | None = Field(
        None, title='Is Not Editable For Children'
    )
    knowledge_topic_schemas: list[str] | None = Field(
        None, title='Knowledge Topic Schemas'
    )
    library_ids: list[str] | None = Field(None, title='Library Ids')


class UpdateUnderlyingSchemaResponse(BaseModel):
    success: bool = Field(..., title='Success')
    message: str = Field(..., title='Message')
    new_ku_schema_history_id: str | None = Field(None, title='New Ku Schema History Id')
    new_ku_schema_id: str | None = Field(None, title='New Ku Schema Id')
    new_ku_schema_version: str | None = Field(None, title='New Ku Schema Version')
    kt_results: list[KtSyncResult] | None = Field(None, title='Kt Results')


class UseCaseAvailableRelation(BaseModel):
    relation_name: str = Field(..., title='Relation Name')
    target_knowledge_topic: str = Field(..., title='Target Knowledge Topic')


class UseCaseColumnView(BaseModel):
    relation_name: str = Field(..., title='Relation Name')
    target_knowledge_topic_name: str = Field(..., title='Target Knowledge Topic Name')
    target_knowledge_topic_history_id: str | None = Field(
        None, title='Target Knowledge Topic History Id'
    )
    allow_multiple: bool | None = Field(False, title='Allow Multiple')
    additional_field: str | None = Field(None, title='Additional Field')
    bidirection: bool = Field(..., title='Bidirection')
    description: str | None = Field(None, title='Description')
    field: str | None = Field('', title='Field')
    additional_field_key: str | None = Field(None, title='Additional Field Key')


class UseCaseDuplicateTopic(BaseModel):
    name: str = Field(..., title='Name')
    count: int = Field(..., title='Count')


class Status1(StrEnum):
    complete = 'complete'
    incomplete = 'incomplete'
    duplicate = 'duplicate'


class UseCaseStatusView(BaseModel):
    use_case_name: str = Field(..., title='Use Case Name')
    status: Status1 = Field(..., title='Status')
    missing_topics: list[str] | None = Field([], title='Missing Topics')
    duplicate_topics: list[UseCaseDuplicateTopic] | None = Field(
        [], title='Duplicate Topics', validate_default=True
    )
    available_topics: list[str] | None = Field([], title='Available Topics')
    required_topics: list[str] | None = Field([], title='Required Topics')
    available_relations: list[UseCaseAvailableRelation] | None = Field(
        [], title='Available Relations', validate_default=True
    )
    is_valid: bool = Field(..., title='Is Valid')
    show_banner: bool = Field(..., title='Show Banner')


class ValidationError(BaseModel):
    loc: list[str | int] = Field(..., title='Location')
    msg: str = Field(..., title='Message')
    type: str = Field(..., title='Error Type')
    input: Any | None = Field(None, title='Input')
    ctx: dict[str, Any] | None = Field(None, title='Context')


class ApplyUnderlyingSchemaResponse(BaseModel):
    success: bool = Field(..., title='Success')
    message: str = Field(..., title='Message')
    applied_ku_schema_history_id: str | None = Field(
        None, title='Applied Ku Schema History Id'
    )
    applied_ku_schema_id: str | None = Field(None, title='Applied Ku Schema Id')
    applied_ku_schema_version: str | None = Field(
        None, title='Applied Ku Schema Version'
    )
    kt_results: list[KtSyncResult] | None = Field(None, title='Kt Results')


class AuditInfo(BaseModel):
    user_id_created: str = Field(..., title='User Id Created')
    timestamp_created: datetime_aliased = Field(..., title='Timestamp Created')
    user_id_last_updated: str | None = Field(None, title='User Id Last Updated')
    timestamp_last_updated: datetime_aliased | None = Field(
        None, title='Timestamp Last Updated'
    )
    last_action: LastActionType
    direct_approval_published_at: datetime_aliased | None = Field(
        None, title='Direct Approval Published At'
    )
    direct_approval_published_by: str | None = Field(
        None, title='Direct Approval Published By'
    )


class BaseLibraryResponse(BaseModel):
    id: str = Field(..., examples=['5eb7cf5a86d9755df3a6c593'], title='Id')
    name: str = Field(..., title='Name')
    description: str | None = Field(None, title='Description')
    metadata: TenantMetadata
    audit_info: AuditInfo


class ConditionalField(BaseModel):
    key: str = Field(..., title='Key')
    input_type: InputType
    status: ConditionalFieldStatus
    hide_expression: str = Field(..., title='Hide Expression')


class CreateKnowledgeBase(BaseModel):
    knowledge_unit_name: str = Field(..., title='Knowledge Unit Name')
    is_not_editable_for_children: bool | None = Field(
        False, title='Is Not Editable For Children'
    )
    parent_entity: ParentEntity


class CreateKnowledgeTopic(BaseModel):
    knowledge_topic_name: str = Field(..., title='Knowledge Topic Name')
    knowledge_topic_schema: dict[str, Any] = Field(..., title='Knowledge Topic Schema')
    related_form_id: str = Field(..., title='Related Form Id')
    type: KnowledgeTopicType
    product_data_collection_id: str | None = Field(
        None, title='Product Data Collection Id'
    )
    external_source: NoExternalSource | ExternalSourceInfo | None = Field(
        None, title='External Source'
    )
    from_existing: CreateKnowledgeTopicFromExisting | None = None


class CreateKnowledgeTopicSchema(BaseModel):
    knowledge_topic_name: str = Field(..., title='Knowledge Topic Name')
    component_schema: dict[str, Any] | None = Field(None, title='Component Schema')
    type: KnowledgeTopicType
    product_data_collection_id: str | None = Field(
        None, title='Product Data Collection Id'
    )
    data: dict[str, Any] | None = Field(None, title='Data')
    knowledge_unit_schema_history_id: str = Field(
        ...,
        examples=['5eb7cf5a86d9755df3a6c593'],
        title='Knowledge Unit Schema History Id',
    )
    from_existing: CreateKnowledgeTopicSchemaFromExisting | None = None


class CreateKnowledgeTopicsFromExisting(BaseModel):
    kt_schema_ids: list[str] | None = Field(
        None,
        description='ID of existing knowledge topic schema to copy from',
        title='Kt Schema Ids',
    )
    kt_ids: list[str] | None = Field(
        None, description='ID of knowledge topic to create schema from', title='Kt Ids'
    )
    include_content: bool | None = Field(
        False,
        description='Whether to include content in the copy',
        title='Include Content',
    )
    include_traces: bool | None = Field(
        True,
        description='Whether to include traces in the copy',
        title='Include Traces',
    )
    knowledge_unit_history_id: str | None = Field(
        '',
        description='knowledge unit history id to add the knowledge topics',
        title='Knowledge Unit History Id',
    )
    parent_entity: ParentEntity


class CreateKnowledgeUnitsFromExisting(BaseModel):
    ku_schema_ids: list[str] | None = Field(
        None,
        description='ID of existing knowledge unit schema to copy from',
        title='Ku Schema Ids',
    )
    ku_history_ids: list[str] | None = Field(
        None,
        description='History ID of knowledge unit to create schema from',
        title='Ku History Ids',
    )
    include_content: bool | None = Field(
        False,
        description='Whether to include content in the copy',
        title='Include Content',
    )
    include_traces: bool | None = Field(
        True,
        description='Whether to include traces in the copy',
        title='Include Traces',
    )
    ignore_knowledge_topics: bool | None = Field(
        None,
        description='Whether to ignore knowledge topics in the copy',
        title='Ignore Knowledge Topics',
    )
    parent_entity: ParentEntity
    product_history_id: str | None = Field(
        '',
        description='Target product history id to add the knowledge units',
        title='Product History Id',
    )
    create_from_unapproved_schemas: bool | None = Field(
        False,
        description='Whether to create from unapproved schemas',
        title='Create From Unapproved Schemas',
    )


class DuplicateKnowledgeUnit(BaseModel):
    ku_schema_id: str | None = Field(
        None,
        description='ID of existing knowledge unit schema to copy from',
        title='Ku Schema Id',
    )
    ku_history_id: str | None = Field(
        None,
        description='ID of knowledge unit to create schema from',
        title='Ku History Id',
    )
    include_content: bool | None = Field(
        False,
        description='Whether to include content in the copy',
        title='Include Content',
    )
    product_history_id: str = Field(..., title='Product History Id')
    parent_entity: ParentEntity


class GuidancePhaseResponse(BaseModel):
    id: str = Field(..., examples=['5eb7cf5a86d9755df3a6c593'], title='Id')
    title: str = Field(..., title='Title')
    goal: str = Field(..., title='Goal')
    tasks: list[GuidanceTaskResponse] = Field(..., title='Tasks')


class HTTPValidationError(BaseModel):
    detail: list[ValidationError] | None = Field(None, title='Detail')


class KnowledgeTopic(BaseModel):
    field_id: str | None = Field(
        None, alias='_id', description='MongoDB document ObjectID', title='Id'
    )
    knowledge_topic_name: str = Field(..., title='Knowledge Topic Name')
    type: KnowledgeTopicType
    knowledge_topic_history_id: str | None = Field(
        None, examples=['5eb7cf5a86d9755df3a6c593'], title='Knowledge Topic History Id'
    )
    product_history_id: str = Field(
        ..., examples=['5eb7cf5a86d9755df3a6c593'], title='Product History Id'
    )
    product_version: str | None = Field('0.1', title='Product Version')
    knowledge_unit_history_id: str = Field(
        ..., examples=['5eb7cf5a86d9755df3a6c593'], title='Knowledge Unit History Id'
    )
    knowledge_unit_version: str = Field(..., title='Knowledge Unit Version')
    knowledge_topic_schema: dict[str, Any] = Field(..., title='Knowledge Topic Schema')
    source_schema_id: str | None = Field(None, title='Source Schema Id')
    data: dict[str, Any] | None = Field({}, title='Data')
    product_data_collection_id: str | None = Field(
        None, title='Product Data Collection Id'
    )
    external_source: NoExternalSource | ExternalSourceInfo | None = Field(
        None, title='External Source'
    )
    metadata: TenantMetadata
    audit_info: AuditInfo | None = None


class KnowledgeTopicOverviewResponse(BaseModel):
    id: str = Field(..., title='Id')
    type: KnowledgeTopicType
    knowledge_topic_history_id: str = Field(
        ..., examples=['5eb7cf5a86d9755df3a6c593'], title='Knowledge Topic History Id'
    )
    knowledge_unit_name: str = Field(..., title='Knowledge Unit Name')
    knowledge_topic_name: str = Field(..., title='Knowledge Topic Name')
    knowledge_topic_schema: dict[str, Any] | None = Field(
        None, title='Knowledge Topic Schema'
    )
    knowledge_unit_revision_id: str | None = Field(
        None, title='Knowledge Unit Revision Id'
    )
    knowledge_unit_history_id: str = Field(
        ..., examples=['5eb7cf5a86d9755df3a6c593'], title='Knowledge Unit History Id'
    )
    knowledge_unit_version: str = Field(..., title='Knowledge Unit Version')
    product_revision_id: str | None = Field(None, title='Product Revision Id')
    product_history_id: str = Field(
        ..., examples=['5eb7cf5a86d9755df3a6c593'], title='Product History Id'
    )
    product_version: str | None = Field(None, title='Product Version')
    product_name: str | None = Field(None, title='Product Name')
    from_family: bool = Field(..., title='From Family')
    latest_revision_id: str | None = Field(None, title='Latest Revision Id')
    latest_or_latest_approved_revision_id: str | None = Field(
        None, title='Latest Or Latest Approved Revision Id'
    )
    traces: list[TraceInfo] | None = Field([], title='Traces', validate_default=True)


class KnowledgeTopicSchema(BaseModel):
    field_id: str | None = Field(
        None, alias='_id', description='MongoDB document ObjectID', title='Id'
    )
    knowledge_topic_name: str = Field(..., title='Knowledge Topic Name')
    component_schema: dict[str, Any] | None = Field({}, title='Component Schema')
    type: KnowledgeTopicType
    knowledge_topic_schema_history_id: str | None = Field(
        None,
        examples=['5eb7cf5a86d9755df3a6c593'],
        title='Knowledge Topic Schema History Id',
    )
    knowledge_unit_schema_history_id: str = Field(
        ...,
        examples=['5eb7cf5a86d9755df3a6c593'],
        title='Knowledge Unit Schema History Id',
    )
    knowledge_unit_schema_name: str = Field(..., title='Knowledge Unit Schema Name')
    knowledge_unit_schema_version: str = Field(
        ..., title='Knowledge Unit Schema Version'
    )
    data: dict[str, Any] | None = Field({}, title='Data')
    product_data_collection_id: str | None = Field(
        None, title='Product Data Collection Id'
    )
    metadata: TenantMetadata
    audit_info: AuditInfo | None = None


class KnowledgeUnit(BaseModel):
    field_id: str | None = Field(
        None, alias='_id', description='MongoDB document ObjectID', title='Id'
    )
    knowledge_unit_name: str = Field(..., title='Knowledge Unit Name')
    knowledge_unit_description: str | None = Field(
        '', title='Knowledge Unit Description'
    )
    parent_entity: ParentEntity
    product_history_id: str = Field(
        ..., examples=['5eb7cf5a86d9755df3a6c593'], title='Product History Id'
    )
    product_version: str | None = Field('0.1', title='Product Version')
    source_schema_id: str | None = Field(None, title='Source Schema Id')
    knowledge_topics: list[KnowledgeTopic1] | None = Field(
        None, title='Knowledge Topics'
    )
    ordered_knowledge_topics: list[OrderedKnowledgeTopic] | None = Field(
        None, title='Ordered Knowledge Topics'
    )
    is_not_editable_for_children: bool | None = Field(
        False, title='Is Not Editable For Children'
    )
    knowledge_unit_history_id: str = Field(
        ..., examples=['5eb7cf5a86d9755df3a6c593'], title='Knowledge Unit History Id'
    )
    major_version: int = Field(..., title='Major Version')
    minor_version: int = Field(..., title='Minor Version')
    is_latest_approved: bool = Field(..., title='Is Latest Approved')
    read_only: bool = Field(..., title='Read Only')
    commit_message: str | None = Field(None, title='Commit Message')
    metadata: TenantMetadata
    audit_info: AuditInfo | None = None


class KnowledgeUnitHistoryGroup(BaseModel):
    knowledge_unit_history_id: str = Field(
        ..., examples=['5eb7cf5a86d9755df3a6c593'], title='Knowledge Unit History Id'
    )
    name: str = Field(..., title='Name')
    latest_revision: KnowledgeUnitRevisionSummary
    latest_approved: KnowledgeUnitRevisionSummary | None = None
    revisions: list[KnowledgeUnitRevisionSummary] | None = Field(
        None, title='Revisions'
    )
    total_revisions: int | None = Field(0, title='Total Revisions')
    related_product_name: str = Field(..., title='Related Product Name')
    parent_entity: ParentEntity
    product_history_id: str | None = Field(None, title='Product History Id')
    product_family_history_id: str | None = Field(
        None, title='Product Family History Id'
    )
    revision_at_product_version: KnowledgeUnitRevisionSummary | None = None


class KnowledgeUnitHistoryGroupSlim(BaseModel):
    knowledge_unit_history_id: str = Field(
        ..., examples=['5eb7cf5a86d9755df3a6c593'], title='Knowledge Unit History Id'
    )
    name: str = Field(..., title='Name')
    related_product_name: str = Field(..., title='Related Product Name')
    parent_entity: ParentEntity
    product_history_id: str | None = Field(None, title='Product History Id')
    product_family_history_id: str | None = Field(
        None, title='Product Family History Id'
    )
    latest_revision: KnowledgeUnitRevisionSlim
    latest_approved: KnowledgeUnitRevisionSlim | None = None
    revisions: list[KnowledgeUnitRevisionSlim] | None = Field(None, title='Revisions')


class KnowledgeUnitSchema(BaseModel):
    field_id: str | None = Field(
        None, alias='_id', description='MongoDB document ObjectID', title='Id'
    )
    knowledge_unit_name: str = Field(..., title='Knowledge Unit Name')
    knowledge_unit_description: str | None = Field(
        None, title='Knowledge Unit Description'
    )
    knowledge_topic_schemas: list[KnowledgeTopicSchema1] | None = Field(
        None, title='Knowledge Topic Schemas'
    )
    ordered_knowledge_topic_schemas: list[OrderedKnowledgeTopicSchema] | None = Field(
        None, title='Ordered Knowledge Topic Schemas'
    )
    libraries: list[Library] | None = Field(None, title='Libraries')
    is_not_editable_for_children: bool | None = Field(
        False, title='Is Not Editable For Children'
    )
    knowledge_unit_schema_history_id: str = Field(
        ...,
        examples=['5eb7cf5a86d9755df3a6c593'],
        title='Knowledge Unit Schema History Id',
    )
    major_version: int = Field(..., title='Major Version')
    minor_version: int = Field(..., title='Minor Version')
    is_latest_approved: bool = Field(..., title='Is Latest Approved')
    read_only: bool = Field(..., title='Read Only')
    commit_message: str | None = Field(None, title='Commit Message')
    metadata: TenantMetadata
    audit_info: AuditInfo | None = None


class KnowledgeUnitSchemaHistoryGroup(BaseModel):
    knowledge_unit_schema_history_id: str = Field(
        ...,
        examples=['5eb7cf5a86d9755df3a6c593'],
        title='Knowledge Unit Schema History Id',
    )
    name: str = Field(..., title='Name')
    latest_revision: KnowledgeUnitSchemaRevisionSummary
    latest_approved: KnowledgeUnitSchemaRevisionSummary | None = None
    revisions: list[KnowledgeUnitSchemaRevisionSummary] | None = Field(
        None, title='Revisions'
    )
    total_revisions: int | None = Field(0, title='Total Revisions')


class KnowledgeUnitSchemaLibrary(BaseModel):
    field_id: str | None = Field(
        None, alias='_id', description='MongoDB document ObjectID', title='Id'
    )
    name: str = Field(..., title='Name')
    description: str | None = Field(None, title='Description')
    knowledge_unit_schemas: list[KnowledgeUnitSchema1] | None = Field(
        [], title='Knowledge Unit Schemas', validate_default=True
    )
    metadata: TenantMetadata
    audit_info: AuditInfo


class KnowledgeUnitUpdate(BaseModel):
    knowledge_unit_name: str | None = Field(None, title='Knowledge Unit Name')
    knowledge_unit_description: str | None = Field(
        None, title='Knowledge Unit Description'
    )
    knowledge_topics: list[KnowledgeTopicUpdate] | None = Field(
        None, title='Knowledge Topics'
    )
    is_not_editable_for_children: bool | None = Field(
        False, title='Is Not Editable For Children'
    )
    parent_entity: str | None = Field(None, title='Parent Entity')
    external_source: NoExternalSource | ExternalSourceInfo | None = Field(
        None, title='External Source'
    )


class ProductAnalytics(BaseModel):
    product_id: str = Field(..., title='Product Id')
    product_name: str = Field(..., title='Product Name')
    product_fields: ProductFields
    knowledge_unit_count: int = Field(..., title='Knowledge Unit Count')
    ku_statistics: list[KUStatistics] = Field(..., title='Ku Statistics')


class ProductFamilyAnalytics(BaseModel):
    product_family_id: str = Field(..., title='Product Family Id')
    product_family_name: str = Field(..., title='Product Family Name')
    product_family_fields: ProductFamilyFields
    knowledge_unit_count: int = Field(..., title='Knowledge Unit Count')
    ku_statistics: list[KUStatistics] = Field(..., title='Ku Statistics')


class ProductFamilyHistoryGroup(BaseModel):
    product_family_history_id: str = Field(
        ..., examples=['5eb7cf5a86d9755df3a6c593'], title='Product Family History Id'
    )
    name: str = Field(..., title='Name')
    latest_revision: ProductFamilyRevisionSummary
    latest_approved: ProductFamilyRevisionSummary | None = None
    revisions: list[ProductFamilyRevisionSummary] | None = Field(
        None, title='Revisions'
    )
    total_revisions: int | None = Field(0, title='Total Revisions')


class ProductHistoryGroup(BaseModel):
    product_history_id: str = Field(
        ..., examples=['5eb7cf5a86d9755df3a6c593'], title='Product History Id'
    )
    name: str = Field(..., title='Name')
    latest_revision: ProductRevisionSummary
    latest_approved: ProductRevisionSummary | None = None
    revisions: list[ProductRevisionSummary] | None = Field(None, title='Revisions')
    total_revisions: int | None = Field(0, title='Total Revisions')


class ProductProperties(BaseModel):
    regulation: Regulation
    risk_class: RiskClass
    sterile: bool | None = Field(None, title='Sterile')
    reusable: Reusable | None = None
    measurement: bool | None = Field(None, title='Measurement')
    active: bool | None = Field(None, title='Active')
    invasive: bool | None = Field(None, title='Invasive')
    implantable: bool | None = Field(None, title='Implantable')
    medicinal_product: bool | None = Field(None, title='Medicinal Product')
    software: Software | None = 'NoSoftware'
    software_class: SoftwareClass | None = 'NoSoftware'
    biocompatibility: bool | None = Field(None, title='Biocompatibility')
    clinical_evaluation: bool | None = Field(None, title='Clinical Evaluation')
    performance_evaluation: bool | None = Field(None, title='Performance Evaluation')
    reprocessing: bool | None = Field(None, title='Reprocessing')
    reagents: bool | None = Field(None, title='Reagents')


class PublishKnowledgeUnitResponse(BaseModel):
    success: bool = Field(..., title='Success')
    commit_message: str = Field(..., title='Commit Message')
    knowledge_unit: KnowledgeUnit | None = None


class PublishKnowledgeUnitSchemaResponse(BaseModel):
    success: bool = Field(..., title='Success')
    commit_message: str = Field(..., title='Commit Message')
    knowledge_unit_schema: KnowledgeUnitSchema | None = None


class RecordFields(BaseModel):
    record_id: str = Field(..., title='Record Id')
    present_fields: dict[str, InputType] = Field(..., title='Present Fields')
    missing_fields: dict[str, InputType] = Field(..., title='Missing Fields')
    conditional_fields: list[ConditionalField] | None = Field(
        [], title='Conditional Fields', validate_default=True
    )
    missing_field_names: list[MissingFieldName] | None = Field(
        [], title='Missing Field Names', validate_default=True
    )


class RecordsSummary(BaseModel):
    records: list[RecordFields] = Field(..., title='Records')
    records_with_missing_fields: int = Field(..., title='Records With Missing Fields')
    input_types: dict[str, InputType] = Field(..., title='Input Types')


class RiskAnalysisMatrixResponse(BaseModel):
    rows: list[RiskAnalysisMatrixRow] | None = Field(
        [], title='Rows', validate_default=True
    )
    forms: dict[str, dict[str, Any]] | None = Field({}, title='Forms')


class SchemaKnowledgeTopic(BaseModel):
    id: str | None = Field(None, title='Id')
    knowledge_topic_name: str = Field(..., title='Knowledge Topic Name')
    type: KnowledgeTopicType
    knowledge_topic_schema: SchemaKnowledgeTopicSchema


class SchemaKnowledgeUnit(BaseModel):
    id: str | None = Field(None, title='Id')
    knowledge_unit_name: str = Field(..., title='Knowledge Unit Name')
    knowledge_topics: list[SchemaKnowledgeTopic] = Field(..., title='Knowledge Topics')


class SlimProductView(BaseModel):
    field_id: str | None = Field(
        None, alias='_id', description='MongoDB document ObjectID', title='Id'
    )
    name: str = Field(..., title='Name')
    udi: str | None = Field(None, title='Udi')
    udi_issuer: IssuingEntityTypeEnum | None = None
    udi_di: str | None = Field('N/A', title='Udi Di')
    lot_number: str | None = Field(None, title='Lot Number')
    serial_number: str | None = Field(None, title='Serial Number')
    notified_body: str | None = Field(None, title='Notified Body')
    ce_certificate_number: str | None = Field(None, title='Ce Certificate Number')
    product_properties: ProductProperties
    regulatory_status: str | None = Field(None, title='Regulatory Status')
    product_context: list[ProductContextQuestion] | None = Field(
        None, title='Product Context'
    )
    product_website: str | None = Field(None, title='Product Website')
    product_families: list[SlimProductFamilyRef] | None = Field(
        None, title='Product Families'
    )
    knowledge_units: list[SlimKnowledgeUnitRef] | None = Field(
        None, title='Knowledge Units'
    )
    product_history_id: str = Field(
        ..., examples=['5eb7cf5a86d9755df3a6c593'], title='Product History Id'
    )
    major_version: int = Field(..., title='Major Version')
    minor_version: int = Field(..., title='Minor Version')
    is_latest_approved: bool = Field(..., title='Is Latest Approved')
    read_only: bool = Field(..., title='Read Only')
    commit_message: str | None = Field(None, title='Commit Message')
    metadata: TenantMetadata
    audit_info: AuditInfo


class UnderlyingSchemaApplyStatus(BaseModel):
    eligible: bool | None = Field(False, title='Eligible')
    out_of_sync: bool | None = Field(False, title='Out Of Sync')
    topics: list[UnderlyingSchemaSyncTopic] | None = Field(None, title='Topics')
    latest_approved_schema_version: str | None = Field(
        None, title='Latest Approved Schema Version'
    )


class UnderlyingSchemaSyncStatus(BaseModel):
    eligible: bool | None = Field(False, title='Eligible')
    out_of_sync: bool | None = Field(False, title='Out Of Sync')
    ku_changed: bool | None = Field(False, title='Ku Changed')
    topics: list[UnderlyingSchemaSyncTopic] | None = Field(None, title='Topics')
    compared_schema_version: str | None = Field(None, title='Compared Schema Version')


class UpdateProduct(BaseModel):
    name: str | None = Field(None, title='Name')
    udi: str | None = Field(None, title='Udi')
    udi_issuer: IssuingEntityTypeEnum | None = None
    udi_di: str | None = Field(None, title='Udi Di')
    lot_number: str | None = Field(None, title='Lot Number')
    serial_number: str | None = Field(None, title='Serial Number')
    notified_body: str | None = Field(None, title='Notified Body')
    ce_certificate_number: str | None = Field(None, title='Ce Certificate Number')
    regulatory_status: str | None = Field(None, title='Regulatory Status')
    product_properties: ProductProperties | None = None
    product_families: list[str] | None = Field(None, title='Product Families')
    product_context: list[ProductContextQuestion] | None = Field(
        None, title='Product Context'
    )
    product_website: str | None = Field(None, title='Product Website')


class UpdateProductFamily(BaseModel):
    name: str | None = Field(None, title='Name')
    udi: str | None = Field(None, title='Udi')
    udi_issuer: IssuingEntityTypeEnum | None = None
    lot_number: str | None = Field(None, title='Lot Number')
    serial_number: str | None = Field(None, title='Serial Number')
    notified_body: str | None = Field(None, title='Notified Body')
    ce_certificate_number: str | None = Field(None, title='Ce Certificate Number')
    regulatory_status: str | None = Field(None, title='Regulatory Status')
    product_properties: ProductProperties | None = None


class UseCaseConfigView(BaseModel):
    columns: list[UseCaseColumnView] | None = Field(
        [], title='Columns', validate_default=True
    )
    status: list[UseCaseStatusView] | None = Field(
        [], title='Status', validate_default=True
    )


class BodyCreateKnowledgeUnitKuPost(BaseModel):
    knowledge_unit: CreateKnowledgeBase
    product_history_id: str = Field(
        ..., examples=['5eb7cf5a86d9755df3a6c593'], title='Product History Id'
    )


class BodyCreateNewKnowledgeTopicKtPost(BaseModel):
    knowledge_topic: CreateKnowledgeTopic
    knowledge_unit_history_id: str = Field(
        ..., examples=['5eb7cf5a86d9755df3a6c593'], title='Knowledge Unit History Id'
    )


class CommitKnowledgeUnitResponse(BaseModel):
    success: bool = Field(..., title='Success')
    commit_message: str = Field(..., title='Commit Message')
    knowledge_unit: KnowledgeUnit | None = None


class CommitKnowledgeUnitSchemaResponse(BaseModel):
    success: bool = Field(..., title='Success')
    commit_message: str = Field(..., title='Commit Message')
    knowledge_unit_schema: KnowledgeUnitSchema | None = None


class CreateKnowledgeTopicSchemasResponse(BaseModel):
    data: list[KnowledgeTopicSchema] = Field(
        ..., description='Array of successfully created schemas', title='Data'
    )
    skipped_knowledge_topics: list[SkippedKnowledgeTopic] | None = Field(
        None,
        description='Array of skipped knowledge topics with their reasons',
        title='Skipped Knowledge Topics',
    )


class CreateKnowledgeUnitSchemasResponse(BaseModel):
    data: list[KnowledgeUnitSchema] = Field(
        ..., description='Array of successfully created schemas', title='Data'
    )
    skipped_knowledge_topics: list[SkippedKnowledgeTopic] | None = Field(
        None,
        description='Array of skipped knowledge topics with their reasons',
        title='Skipped Knowledge Topics',
    )


class CreateProduct(BaseModel):
    name: str = Field(..., title='Name')
    product_properties: ProductProperties
    udi: str | None = Field(None, title='Udi')
    udi_issuer: IssuingEntityTypeEnum | None = None
    udi_di: str | None = Field('N/A', title='Udi Di')
    product_families: list[str] | None = Field(None, title='Product Families')
    product_context: list[ProductContextQuestion] | None = Field(
        None, title='Product Context'
    )
    product_website: str | None = Field(None, title='Product Website')


class CreateProductFamily(BaseModel):
    name: str = Field(..., title='Name')
    product_properties: ProductProperties


class FullKnowledgeUnitView(BaseModel):
    knowledge_unit_name: str = Field(..., title='Knowledge Unit Name')
    knowledge_unit_description: str | None = Field(
        '', title='Knowledge Unit Description'
    )
    parent_entity: ParentEntity
    product_history_id: str = Field(
        ..., examples=['5eb7cf5a86d9755df3a6c593'], title='Product History Id'
    )
    product_version: str | None = Field('0.1', title='Product Version')
    source_schema_id: str | None = Field(None, title='Source Schema Id')
    knowledge_topics: list[KnowledgeTopic] | None = Field(
        [], title='Knowledge Topics', validate_default=True
    )
    ordered_knowledge_topics: list[OrderedKnowledgeTopic] | None = Field(
        None, title='Ordered Knowledge Topics'
    )
    is_not_editable_for_children: bool | None = Field(
        False, title='Is Not Editable For Children'
    )
    knowledge_unit_history_id: str = Field(
        ..., examples=['5eb7cf5a86d9755df3a6c593'], title='Knowledge Unit History Id'
    )
    major_version: int = Field(..., title='Major Version')
    minor_version: int = Field(..., title='Minor Version')
    is_latest_approved: bool = Field(..., title='Is Latest Approved')
    read_only: bool = Field(..., title='Read Only')
    commit_message: str | None = Field(None, title='Commit Message')
    metadata: TenantMetadata
    audit_info: AuditInfo | None = None
    id: str = Field(..., examples=['5eb7cf5a86d9755df3a6c593'], title='Id')


class FullProductFamilyView(BaseModel):
    field_id: str | None = Field(
        None, alias='_id', description='MongoDB document ObjectID', title='Id'
    )
    name: str = Field(..., title='Name')
    udi: str | None = Field(None, title='Udi')
    udi_issuer: IssuingEntityTypeEnum | None = None
    lot_number: str | None = Field(None, title='Lot Number')
    serial_number: str | None = Field(None, title='Serial Number')
    notified_body: str | None = Field(None, title='Notified Body')
    ce_certificate_number: str | None = Field(None, title='Ce Certificate Number')
    regulatory_status: str | None = Field(None, title='Regulatory Status')
    product_properties: ProductProperties
    knowledge_units: list[FullKnowledgeUnitView] | None = Field(
        [], title='Knowledge Units', validate_default=True
    )
    product_family_history_id: str = Field(
        ..., examples=['5eb7cf5a86d9755df3a6c593'], title='Product Family History Id'
    )
    major_version: int = Field(..., title='Major Version')
    minor_version: int = Field(..., title='Minor Version')
    is_latest_approved: bool = Field(..., title='Is Latest Approved')
    read_only: bool = Field(..., title='Read Only')
    commit_message: str | None = Field(None, title='Commit Message')
    metadata: TenantMetadata
    audit_info: AuditInfo


class FullProductView(BaseModel):
    field_id: str | None = Field(
        None, alias='_id', description='MongoDB document ObjectID', title='Id'
    )
    name: str = Field(..., title='Name')
    udi: str | None = Field(None, title='Udi')
    udi_issuer: IssuingEntityTypeEnum | None = None
    udi_di: str | None = Field('N/A', title='Udi Di')
    lot_number: str | None = Field(None, title='Lot Number')
    serial_number: str | None = Field(None, title='Serial Number')
    notified_body: str | None = Field(None, title='Notified Body')
    ce_certificate_number: str | None = Field(None, title='Ce Certificate Number')
    product_properties: ProductProperties
    regulatory_status: str | None = Field(None, title='Regulatory Status')
    product_context: list[ProductContextQuestion] | None = Field(
        None, title='Product Context'
    )
    product_website: str | None = Field(None, title='Product Website')
    product_families: list[FullProductFamilyView] | None = Field(
        [], title='Product Families', validate_default=True
    )
    knowledge_units: list[FullKnowledgeUnitView] | None = Field(
        [], title='Knowledge Units', validate_default=True
    )
    product_history_id: str = Field(
        ..., examples=['5eb7cf5a86d9755df3a6c593'], title='Product History Id'
    )
    major_version: int = Field(..., title='Major Version')
    minor_version: int = Field(..., title='Minor Version')
    is_latest_approved: bool = Field(..., title='Is Latest Approved')
    read_only: bool = Field(..., title='Read Only')
    commit_message: str | None = Field(None, title='Commit Message')
    metadata: TenantMetadata
    audit_info: AuditInfo


class KTAnalytics(BaseModel):
    knowledge_topic_id: str = Field(..., title='Knowledge Topic Id')
    knowledge_topic_name: str = Field(..., title='Knowledge Topic Name')
    type: KnowledgeTopicType
    records_summary: RecordsSummary
    related_product_id: str = Field(..., title='Related Product Id')
    related_knowledge_unit_id: str = Field(..., title='Related Knowledge Unit Id')


class KnowledgeTopicDetailResponse(BaseModel):
    field_id: str = Field(
        ..., alias='_id', examples=['5eb7cf5a86d9755df3a6c593'], title='Id'
    )
    knowledge_topic_name: str = Field(..., title='Knowledge Topic Name')
    type: KnowledgeTopicType
    knowledge_topic_history_id: str = Field(
        ..., examples=['5eb7cf5a86d9755df3a6c593'], title='Knowledge Topic History Id'
    )
    product_history_id: str = Field(
        ..., examples=['5eb7cf5a86d9755df3a6c593'], title='Product History Id'
    )
    product_version: str = Field(..., title='Product Version')
    knowledge_unit_history_id: str = Field(
        ..., examples=['5eb7cf5a86d9755df3a6c593'], title='Knowledge Unit History Id'
    )
    knowledge_unit_version: str = Field(..., title='Knowledge Unit Version')
    knowledge_topic_schema: dict[str, Any] = Field(..., title='Knowledge Topic Schema')
    source_schema_id: str | None = Field(None, title='Source Schema Id')
    data: dict[str, Any] | None = Field({}, title='Data')
    product_data_collection_id: str | None = Field(
        None, title='Product Data Collection Id'
    )
    metadata: TenantMetadata
    audit_info: AuditInfo | None = None
    latest_revision_id: str | None = Field(None, title='Latest Revision Id')
    latest_or_latest_approved_revision_id: str | None = Field(
        None, title='Latest Or Latest Approved Revision Id'
    )
    use_case_config: UseCaseConfigView | None = None


class KnowledgeTopicSchemaDetailResponse(BaseModel):
    field_id: str = Field(
        ..., alias='_id', examples=['5eb7cf5a86d9755df3a6c593'], title='Id'
    )
    knowledge_topic_name: str = Field(..., title='Knowledge Topic Name')
    component_schema: dict[str, Any] | None = Field({}, title='Component Schema')
    type: KnowledgeTopicType
    knowledge_topic_schema_history_id: str = Field(
        ...,
        examples=['5eb7cf5a86d9755df3a6c593'],
        title='Knowledge Topic Schema History Id',
    )
    knowledge_unit_schema_history_id: str = Field(
        ...,
        examples=['5eb7cf5a86d9755df3a6c593'],
        title='Knowledge Unit Schema History Id',
    )
    knowledge_unit_schema_name: str = Field(..., title='Knowledge Unit Schema Name')
    knowledge_unit_schema_version: str = Field(
        ..., title='Knowledge Unit Schema Version'
    )
    data: dict[str, Any] | None = Field({}, title='Data')
    product_data_collection_id: str | None = Field(
        None, title='Product Data Collection Id'
    )
    metadata: TenantMetadata
    audit_info: AuditInfo | None = None
    use_case_config: UseCaseConfigView | None = None


class KnowledgeTopicWithTraces(BaseModel):
    field_id: str = Field(
        ..., alias='_id', examples=['5eb7cf5a86d9755df3a6c593'], title='Id'
    )
    knowledge_topic_name: str = Field(..., title='Knowledge Topic Name')
    type: KnowledgeTopicType
    knowledge_topic_history_id: str = Field(
        ..., examples=['5eb7cf5a86d9755df3a6c593'], title='Knowledge Topic History Id'
    )
    product_history_id: str = Field(
        ..., examples=['5eb7cf5a86d9755df3a6c593'], title='Product History Id'
    )
    product_version: str = Field(..., title='Product Version')
    knowledge_unit_history_id: str = Field(
        ..., examples=['5eb7cf5a86d9755df3a6c593'], title='Knowledge Unit History Id'
    )
    knowledge_unit_version: str = Field(..., title='Knowledge Unit Version')
    knowledge_topic_schema: dict[str, Any] = Field(..., title='Knowledge Topic Schema')
    source_schema_id: str | None = Field(None, title='Source Schema Id')
    data: dict[str, Any] | None = Field({}, title='Data')
    product_data_collection_id: str | None = Field(
        None, title='Product Data Collection Id'
    )
    metadata: TenantMetadata
    audit_info: AuditInfo | None = None
    latest_revision_id: str | None = Field(None, title='Latest Revision Id')
    latest_or_latest_approved_revision_id: str | None = Field(
        None, title='Latest Or Latest Approved Revision Id'
    )
    use_case_config: UseCaseConfigView | None = None
    external_source: NoExternalSource | ExternalSourceInfo | None = Field(
        None, title='External Source'
    )
    traces: list[TraceInfo] | None = Field([], title='Traces', validate_default=True)


class Product(BaseModel):
    field_id: str | None = Field(
        None, alias='_id', description='MongoDB document ObjectID', title='Id'
    )
    name: str = Field(..., title='Name')
    udi: str | None = Field(None, title='Udi')
    udi_issuer: IssuingEntityTypeEnum | None = None
    udi_di: str | None = Field('N/A', title='Udi Di')
    lot_number: str | None = Field(None, title='Lot Number')
    serial_number: str | None = Field(None, title='Serial Number')
    notified_body: str | None = Field(None, title='Notified Body')
    ce_certificate_number: str | None = Field(None, title='Ce Certificate Number')
    product_properties: ProductProperties
    regulatory_status: str | None = Field(None, title='Regulatory Status')
    product_context: list[ProductContextQuestion] | None = Field(
        None, title='Product Context'
    )
    product_website: str | None = Field(None, title='Product Website')
    product_families: list[ProductFamily] | None = Field(None, title='Product Families')
    knowledge_units: list[KnowledgeUnit1] | None = Field(None, title='Knowledge Units')
    product_history_id: str = Field(
        ..., examples=['5eb7cf5a86d9755df3a6c593'], title='Product History Id'
    )
    major_version: int = Field(..., title='Major Version')
    minor_version: int = Field(..., title='Minor Version')
    is_latest_approved: bool = Field(..., title='Is Latest Approved')
    read_only: bool = Field(..., title='Read Only')
    commit_message: str | None = Field(None, title='Commit Message')
    metadata: TenantMetadata
    audit_info: AuditInfo


class ProductCollection(BaseModel):
    products: list[FullProductView] = Field(..., title='Products')


class ProductFamily1(BaseModel):
    field_id: str | None = Field(
        None, alias='_id', description='MongoDB document ObjectID', title='Id'
    )
    name: str = Field(..., title='Name')
    udi: str | None = Field(None, title='Udi')
    udi_issuer: IssuingEntityTypeEnum | None = None
    lot_number: str | None = Field(None, title='Lot Number')
    serial_number: str | None = Field(None, title='Serial Number')
    notified_body: str | None = Field(None, title='Notified Body')
    ce_certificate_number: str | None = Field(None, title='Ce Certificate Number')
    regulatory_status: str | None = Field(None, title='Regulatory Status')
    product_properties: ProductProperties
    knowledge_units: list[KnowledgeUnit1] | None = Field(None, title='Knowledge Units')
    product_family_history_id: str = Field(
        ..., examples=['5eb7cf5a86d9755df3a6c593'], title='Product Family History Id'
    )
    major_version: int = Field(..., title='Major Version')
    minor_version: int = Field(..., title='Minor Version')
    is_latest_approved: bool = Field(..., title='Is Latest Approved')
    read_only: bool = Field(..., title='Read Only')
    commit_message: str | None = Field(None, title='Commit Message')
    metadata: TenantMetadata
    audit_info: AuditInfo


class ProductFamilyCollection(BaseModel):
    product_families: list[ProductFamily1] = Field(..., title='Product Families')


class PublishProductFamilyResponse(BaseModel):
    success: bool = Field(..., title='Success')
    commit_message: str = Field(..., title='Commit Message')
    product_family: ProductFamily1 | None = None


class PublishProductResponse(BaseModel):
    success: bool = Field(..., title='Success')
    commit_message: str = Field(..., title='Commit Message')
    product: Product | None = None


class SchemaWithLibraries(BaseModel):
    id: str = Field(..., examples=['5eb7cf5a86d9755df3a6c593'], title='Id')
    knowledge_unit_name: str = Field(..., title='Knowledge Unit Name')
    knowledge_unit_description: str | None = Field(
        None, title='Knowledge Unit Description'
    )
    is_not_editable_for_children: bool | None = Field(
        False, title='Is Not Editable For Children'
    )
    metadata: TenantMetadata
    audit_info: AuditInfo | None = None
    knowledge_topic_schemas: list[KnowledgeTopicSchemaDetailResponse] | None = Field(
        [], title='Knowledge Topic Schemas', validate_default=True
    )
    knowledge_unit_schema_history_id: str = Field(
        ...,
        examples=['5eb7cf5a86d9755df3a6c593'],
        title='Knowledge Unit Schema History Id',
    )
    major_version: int = Field(..., title='Major Version')
    minor_version: int = Field(..., title='Minor Version')
    is_latest_approved: bool = Field(..., title='Is Latest Approved')
    read_only: bool = Field(..., title='Read Only')
    commit_message: str | None = Field(None, title='Commit Message')
    libraries: list[BaseLibraryResponse] | None = Field(
        [], title='Libraries', validate_default=True
    )


class SlimProductCollection(BaseModel):
    products: list[SlimProductView] = Field(..., title='Products')


class AnalyticsResponseModel(BaseModel):
    products: list[ProductAnalytics] = Field(..., title='Products')
    kts: list[KTAnalytics] = Field(..., title='Kts')
    product_families: list[ProductFamilyAnalytics] | None = Field(
        [], title='Product Families', validate_default=True
    )


class BulkKnowledgeTopicFetchResult(BaseModel):
    requested_id: str = Field(
        ..., examples=['5eb7cf5a86d9755df3a6c593'], title='Requested Id'
    )
    success: bool = Field(..., title='Success')
    knowledge_topic: KnowledgeTopicDetailResponse | None = None
    error: str | None = Field(None, title='Error')


class BulkKnowledgeUnitFetchResult(BaseModel):
    history_id: str = Field(
        ..., examples=['5eb7cf5a86d9755df3a6c593'], title='History Id'
    )
    success: bool = Field(..., title='Success')
    revision: FullKnowledgeUnitView | None = None
    history: KnowledgeUnitHistoryGroup | None = None
    error: str | None = Field(None, title='Error')


class BulkProductFamilyFetchResult(BaseModel):
    history_id: str = Field(
        ..., examples=['5eb7cf5a86d9755df3a6c593'], title='History Id'
    )
    success: bool = Field(..., title='Success')
    revision: FullProductFamilyView | None = None
    history: ProductFamilyHistoryGroup | None = None
    error: str | None = Field(None, title='Error')


class BulkProductFetchResult(BaseModel):
    history_id: str = Field(
        ..., examples=['5eb7cf5a86d9755df3a6c593'], title='History Id'
    )
    success: bool = Field(..., title='Success')
    revision: FullProductView | None = None
    history: ProductHistoryGroup | None = None
    error: str | None = Field(None, title='Error')


class DuplicateKnowledgeUnitResponse(BaseModel):
    data: FullKnowledgeUnitView = Field(
        ..., description='The duplicated knowledge unit'
    )
    skipped_knowledge_topics: list[SkippedKnowledgeTopic] | None = Field(
        None,
        description='Array of skipped knowledge topics with their reasons',
        title='Skipped Knowledge Topics',
    )


class FullLibraryResponse(BaseModel):
    id: str = Field(..., examples=['5eb7cf5a86d9755df3a6c593'], title='Id')
    name: str = Field(..., title='Name')
    description: str | None = Field(None, title='Description')
    metadata: TenantMetadata
    audit_info: AuditInfo
    knowledge_unit_schemas: list[SchemaWithLibraries] | None = Field(
        [], title='Knowledge Unit Schemas', validate_default=True
    )


class SlimKnowledgeUnitSchemaResponse(BaseModel):
    id: str = Field(..., examples=['5eb7cf5a86d9755df3a6c593'], title='Id')
    knowledge_unit_schema_history_id: str = Field(
        ...,
        examples=['5eb7cf5a86d9755df3a6c593'],
        title='Knowledge Unit Schema History Id',
    )
    knowledge_unit_name: str = Field(..., title='Knowledge Unit Name')
    libraries: list[SlimLibraryResponse] | None = Field(None, title='Libraries')
    major_version: int = Field(..., title='Major Version')
    minor_version: int = Field(..., title='Minor Version')
    is_latest_approved: bool = Field(..., title='Is Latest Approved')
    read_only: bool = Field(..., title='Read Only')


class SlimLibraryResponse(BaseModel):
    id: str = Field(..., examples=['5eb7cf5a86d9755df3a6c593'], title='Id')
    name: str = Field(..., title='Name')
    description: str | None = Field(None, title='Description')
    metadata: TenantMetadata
    audit_info: AuditInfo
    knowledge_unit_schemas: list[SlimKnowledgeUnitSchemaResponse] | None = Field(
        None, title='Knowledge Unit Schemas'
    )


SchemaKnowledgeTopicInput.model_rebuild()
SlimKnowledgeUnitSchemaResponse.model_rebuild()
