# generated by datamodel-codegen:
#   filename:  records.json
#   timestamp: 2026-08-20T08:57:17+00:00

from __future__ import annotations

from datetime import datetime
from enum import StrEnum
from typing import Any

from pydantic import BaseModel, Field, constr


class GlobalElementType(StrEnum):
    product_data_collection = 'product_data_collection'
    system_context_collection = 'system_context_collection'


class GridColumnVisibility(BaseModel):
    field_id: str = Field(..., title='Field Id')
    visible: bool = Field(..., title='Visible')


class GridDensity(StrEnum):
    compact = 'compact'
    standard = 'standard'
    comfortable = 'comfortable'


class GridFilterItem(BaseModel):
    id: int = Field(..., title='Id')
    field: str = Field(..., title='Field')
    operator: str = Field(..., title='Operator')
    value: str | None = Field(None, title='Value')


class GridLogicOperator(StrEnum):
    AND = 'AND'
    OR = 'OR'


class GridSortDirection(StrEnum):
    asc = 'asc'
    desc = 'desc'


class GridSorting(BaseModel):
    field: str = Field(..., title='Field')
    sort: GridSortDirection


class LastActionType(StrEnum):
    created = 'created'
    updated = 'updated'


class LinkedDocument(BaseModel):
    document_id: str | None = Field(None, title='Document Id')
    document_version: str | None = Field(None, title='Document Version')
    template_id: str | None = Field(None, title='Template Id')
    template_version: str | None = Field(None, title='Template Version')


class Category(BaseModel):
    id: str = Field(..., title='Id')
    collection: str = Field(..., title='Collection')


class RecordBulkUpdate(BaseModel):
    ids: list[constr(pattern=r'^[0-9a-f]{24}$', min_length=24, max_length=24)] = Field(
        ..., title='Ids'
    )
    form: dict[str, Any] | None = Field(None, title='Form')


class RecordContext(BaseModel):
    linked_product: str | None = Field(None, title='Linked Product')
    linked_sop: str | None = Field(None, title='Linked Sop')
    form_id: str | None = Field(None, title='Form Id')
    global_element_id: str | None = Field(None, title='Global Element Id')
    knowledge_unit_id: str | None = Field(None, title='Knowledge Unit Id')
    knowledge_unit_topic_id: str | None = Field(None, title='Knowledge Unit Topic Id')
    linked_document: LinkedDocument | None = None
    group_id: str | None = Field(None, title='Group Id')


class RecordCreate(BaseModel):
    name: str = Field(..., title='Name')
    form: dict[str, Any] = Field(..., title='Form')
    data: dict[str, Any] | None = Field(None, title='Data')
    context: RecordContext
    auto_number: bool | None = Field(False, title='Auto Number')
    read_only: bool | None = Field(None, title='Read Only')


class TenantMetadata(BaseModel):
    tenant_id: str = Field(..., title='Tenant Id')


class ValidationError(BaseModel):
    loc: list[str | int] = Field(..., title='Location')
    msg: str = Field(..., title='Message')
    type: str = Field(..., title='Error Type')


class AuditInfo(BaseModel):
    user_id_created: str = Field(..., title='User Id Created')
    timestamp_created: datetime = Field(..., title='Timestamp Created')
    user_id_last_updated: str | None = Field(None, title='User Id Last Updated')
    timestamp_last_updated: datetime | None = Field(
        None, title='Timestamp Last Updated'
    )
    last_action: LastActionType


class GlobalElement(BaseModel):
    field_id: constr(pattern=r'^[0-9a-f]{24}$', min_length=24, max_length=24) | None = (
        Field(None, alias='_id', description='MongoDB document ObjectID')
    )
    name: str = Field(..., title='Name')
    schema_: dict[str, Any] | None = Field(None, alias='schema', title='Schema')
    description: str | None = Field(None, title='Description')
    metadata: TenantMetadata
    audit_info: AuditInfo
    type: GlobalElementType


class GridFilterModel(BaseModel):
    items: list[GridFilterItem] = Field(..., title='Items')
    logicOperator: GridLogicOperator


class GridSettings(BaseModel):
    gridFilterModel: GridFilterModel | None = None
    columnVisibility: list[GridColumnVisibility] | None = Field(
        None, title='Columnvisibility'
    )
    gridDensity: GridDensity | None = None
    sorting: list[GridSorting] | None = Field(None, title='Sorting')


class HTTPValidationError(BaseModel):
    detail: list[ValidationError] | None = Field(None, title='Detail')


class QmList(BaseModel):
    field_id: constr(pattern=r'^[0-9a-f]{24}$', min_length=24, max_length=24) | None = (
        Field(None, alias='_id', description='MongoDB document ObjectID')
    )
    name: str = Field(..., title='Name')
    description: str | None = Field('', title='Description')
    metadata: TenantMetadata
    settings: GridSettings | None = None
    audit_info: AuditInfo
    category: Category | dict[str, Any] | None = Field(None, title='Category')
    filter_tag: str | None = Field(None, title='Filter Tag')
    template_ids: list[str] = Field(..., title='Template Ids')


class Record(BaseModel):
    field_id: constr(pattern=r'^[0-9a-f]{24}$', min_length=24, max_length=24) | None = (
        Field(None, alias='_id', description='MongoDB document ObjectID')
    )
    name: str = Field(..., title='Name')
    form: dict[str, Any] = Field(..., title='Form')
    version: str = Field(..., title='Version')
    data: dict[str, Any] = Field(..., title='Data')
    read_only: bool | None = Field(False, title='Read Only')
    metadata: TenantMetadata
    context: RecordContext | None
    audit_info: AuditInfo
