"""Sync CertHub export into Sphinx-Needs RST and a normalized snapshot."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from certhub_connector.config import CerthubConfig
from certhub_connector.config.paths import (
    certhub_generated_dir,
    normalized_snapshot_path,
    sphinx_generated_dir,
)
from certhub_connector.sync.models import (
    CertHubExport,
    DesignOutput,
    RequirementBase,
    Validation,
    Verification,
)
from certhub_connector.sync.sources import CertHubExportSource, HttpKtExportSource

GENERATED_HEADER = (
    ".. GENERATED by cadence sync — DO NOT EDIT BY HAND\n"
    "..\n"
    ".. Overwritten on every sync from CertHub APIs.\n"
    "\n"
)


def _escape_rst(text: str) -> str:
    return text.replace("\\", "\\\\").replace("*", "\\*").replace("`", "\\`")


def _optional_option(name: str, value: str | None) -> list[str]:
    if value is None or not value.strip():
        return []
    return [f"   :{name}: {_escape_rst(value.strip())}"]


def _optional_list_option(name: str, values: list[str]) -> list[str]:
    if not values:
        return []
    return [f"   :{name}: {';'.join(values)}"]


def _req_options(
    req: RequirementBase,
    *,
    directive: str,
    project_version: str,
) -> list[str]:
    external_id = req.external_id or req.id
    lines = [
        f".. {directive}:: {_escape_rst(req.title)}",
        f"   :id: {req.id}",
        f"   :status: {req.status}",
        "   :source_system: CertHub",
        f"   :external_id: {_escape_rst(external_id)}",
        f"   :external_version: {project_version}",
    ]
    lines.extend(_optional_option("req_type", req.req_type))
    lines.extend(_optional_option("priority", req.priority))
    lines.extend(_optional_option("source", req.source))
    lines.extend(_optional_option("justification", req.justification))
    if req.concerning:
        lines.extend(_optional_option("concerning", "; ".join(req.concerning)))
    lines.extend(_optional_list_option("links", req.links))
    return lines


def _need_rst(
    export: CertHubExport,
    *,
    directive: str,
    items: list[Any],
    extra_options: list[tuple[str, Any]] | None = None,
) -> str:
    lines = [GENERATED_HEADER]
    for item in items:
        if isinstance(item, RequirementBase):
            lines.extend(
                _req_options(item, directive=directive, project_version=export.project.version)
            )
        elif isinstance(item, DesignOutput):
            external_id = item.external_id or item.id
            lines.extend(
                [
                    f".. dout:: {_escape_rst(item.title)}",
                    f"   :id: {item.id}",
                    f"   :status: {item.status}",
                    "   :source_system: CertHub",
                    f"   :external_id: {_escape_rst(external_id)}",
                    f"   :external_version: {export.project.version}",
                ]
            )
            lines.extend(_optional_list_option("links", item.links))
        elif isinstance(item, Verification):
            external_id = item.external_id or item.id
            lines.extend(
                [
                    f".. verif:: {_escape_rst(item.title)}",
                    f"   :id: {item.id}",
                    f"   :status: {item.status}",
                    "   :source_system: CertHub",
                    f"   :external_id: {_escape_rst(external_id)}",
                    f"   :external_version: {export.project.version}",
                ]
            )
            lines.extend(_optional_list_option("links", item.links))
            lines.extend(_optional_list_option("verifies", item.verifies))
        elif isinstance(item, Validation):
            external_id = item.external_id or item.id
            lines.extend(
                [
                    f".. valid:: {_escape_rst(item.title)}",
                    f"   :id: {item.id}",
                    f"   :status: {item.status}",
                    "   :source_system: CertHub",
                    f"   :external_id: {_escape_rst(external_id)}",
                    f"   :external_version: {export.project.version}",
                ]
            )
            lines.extend(_optional_list_option("links", item.links))
        else:
            raise TypeError(f"Unsupported need type for RST: {type(item)!r}")
        if extra_options:
            for name, value in extra_options:
                if isinstance(value, list):
                    lines.extend(_optional_list_option(name, value))
                else:
                    lines.extend(_optional_option(name, str(value) if value else None))
        lines.extend(["", f"   {_escape_rst(item.description)}", ""])
    return "\n".join(lines)


def write_generated_files(export: CertHubExport) -> list[Path]:
    """Write RST + normalized JSON snapshot. Returns written paths."""
    docs_dir = sphinx_generated_dir()
    cert_dir = certhub_generated_dir()
    docs_dir.mkdir(parents=True, exist_ok=True)
    cert_dir.mkdir(parents=True, exist_ok=True)

    mapping = {
        docs_dir / "user_requirements.rst": _need_rst(
            export, directive="ureq", items=export.user_requirements
        ),
        docs_dir / "system_requirements.rst": _need_rst(
            export, directive="sysreq", items=export.system_requirements
        ),
        docs_dir / "component_requirements.rst": _need_rst(
            export, directive="creq", items=export.component_requirements
        ),
        docs_dir / "unit_requirements.rst": _need_rst(
            export, directive="unitreq", items=export.unit_requirements
        ),
        docs_dir / "design_outputs.rst": _need_rst(
            export, directive="dout", items=export.design_outputs
        ),
        docs_dir / "verifications.rst": _need_rst(
            export, directive="verif", items=export.verifications
        ),
        docs_dir / "validations.rst": _need_rst(
            export, directive="valid", items=export.validations
        ),
    }

    written: list[Path] = []
    for path, content in mapping.items():
        path.write_text(content, encoding="utf-8")
        written.append(path)

    snapshot = normalized_snapshot_path()
    snapshot.write_text(
        json.dumps(export.model_dump(mode="json"), indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    written.append(snapshot)
    return written


def sync_from_source(source: CertHubExportSource | None = None) -> CertHubExport:
    """Load CertHub export, validate, and generate local Sphinx-Needs sources."""
    if source is None:
        CerthubConfig.load()
        source = HttpKtExportSource()
    export = source.load()
    write_generated_files(export)
    return export
