# generated by datamodel-codegen:
#   filename:  records.json
#   timestamp: 2026-08-08T10:11:02+00:00

from __future__ import annotations

from datetime import datetime
from enum import StrEnum
from typing import Any

from pydantic import BaseModel, ConfigDict, Field, RootModel, constr


class ExportGlobalElementsRequest(BaseModel):
    element_ids: list[str] = Field(
        ..., description='List of global element IDs to export', title='Element Ids'
    )


class GlobalElementType(StrEnum):
    product_data_collection = 'product_data_collection'
    system_context_collection = 'system_context_collection'


class GlobalElementUpdate(BaseModel):
    name: str | None = Field(None, title='Name')
    description: str | None = Field(None, title='Description')
    schema_: dict[str, Any] | None = Field(None, alias='schema', title='Schema')
    type: GlobalElementType | None = None


class GridColumnVisibility(BaseModel):
    field_id: str = Field(..., title='Field Id')
    visible: bool = Field(..., title='Visible')


class GridDensity(StrEnum):
    compact = 'compact'
    standard = 'standard'
    comfortable = 'comfortable'


class GridFilterItem(BaseModel):
    id: int = Field(..., title='Id')
    field: str = Field(..., title='Field')
    operator: str = Field(..., title='Operator')
    value: str | None = Field(None, title='Value')


class GridLogicOperator(StrEnum):
    AND = 'AND'
    OR = 'OR'


class GridSortDirection(StrEnum):
    asc = 'asc'
    desc = 'desc'


class GridSorting(BaseModel):
    field: str = Field(..., title='Field')
    sort: GridSortDirection


class ImportGlobalElementsRequest(BaseModel):
    files: list[str] = Field(
        ..., description='JSON files in string format to import', title='Files'
    )
    type: GlobalElementType = Field(..., description='Type of global element to import')


class ImportGlobalElementsResponse(BaseModel):
    successful_imports: int | None = Field(
        0,
        description='Number of successfully imported global elements',
        title='Successful Imports',
    )
    failed_imports: int | None = Field(
        0, description='Number of failed imports', title='Failed Imports'
    )
    error_details: list[dict[str, Any]] | None = Field(
        None, description='Details of any failed imports', title='Error Details'
    )


class LastActionType(StrEnum):
    created = 'created'
    updated = 'updated'


class LinkedDocument(BaseModel):
    document_id: str | None = Field(None, title='Document Id')
    document_version: str | None = Field(None, title='Document Version')
    template_id: str | None = Field(None, title='Template Id')
    template_version: str | None = Field(None, title='Template Version')


class Category(BaseModel):
    id: str = Field(..., title='Id')
    collection: str = Field(..., title='Collection')


class QmListCategoryCreate(BaseModel):
    name: str = Field(..., title='Name')


class QmListCategoryUpdate(BaseModel):
    name: str = Field(..., title='Name')


class QmListCreate(BaseModel):
    name: str = Field(..., title='Name')
    description: str | None = Field('', title='Description')
    filter_tag: str | None = Field(None, title='Filter Tag')
    template_ids: list[str] = Field(..., title='Template Ids')


class RecordBulkUpdate(BaseModel):
    ids: list[constr(pattern=r'^[0-9a-f]{24}$', min_length=24, max_length=24)] = Field(
        ..., title='Ids'
    )
    form: dict[str, Any] | None = Field(None, title='Form')


class RecordContext(BaseModel):
    linked_product: str | None = Field(None, title='Linked Product')
    linked_sop: str | None = Field(None, title='Linked Sop')
    form_id: str | None = Field(None, title='Form Id')
    global_element_id: str | None = Field(None, title='Global Element Id')
    knowledge_unit_id: str | None = Field(None, title='Knowledge Unit Id')
    knowledge_unit_topic_id: str | None = Field(None, title='Knowledge Unit Topic Id')
    linked_document: LinkedDocument | None = None
    group_id: str | None = Field(None, title='Group Id')


class RecordContextFilter(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id__in: (
        list[constr(pattern=r'^[0-9a-f]{24}$', min_length=24, max_length=24)] | None
    ) = Field(None, title='Id  In')
    context__linked_product: str | None = Field(None, title='Context  Linked Product')
    context__form_id: str | None = Field(None, title='Context  Form Id')
    context__knowledge_unit_id: str | None = Field(
        None, title='Context  Knowledge Unit Id'
    )
    context__knowledge_unit_topic_id: str | None = Field(
        None, title='Context  Knowledge Unit Topic Id'
    )
    context__knowledge_unit_topic_id__in: list[str] | None = Field(
        None, title='Context  Knowledge Unit Topic Id  In'
    )
    context__global_element_id: str | None = Field(
        None, title='Context  Global Element Id'
    )
    context__linked_document__document_id: str | None = Field(
        None, title='Context  Linked Document  Document Id'
    )
    context__linked_document__document_version: str | None = Field(
        None, title='Context  Linked Document  Document Version'
    )
    context__linked_document__template_id: str | None = Field(
        None, title='Context  Linked Document  Template Id'
    )
    context__linked_sop: str | None = Field(None, title='Context  Linked Sop')
    context__filter_tag: str | None = Field(None, title='Context  Filter Tag')
    audit_info__user_id_created: str | None = Field(
        None, title='Audit Info  User Id Created'
    )
    audit_info__start_date: datetime | None = Field(
        None, title='Audit Info  Start Date'
    )
    audit_info__end_date: datetime | None = Field(None, title='Audit Info  End Date')
    audit_info__include_updated: bool | None = Field(
        False, title='Audit Info  Include Updated'
    )


class RecordCreate(BaseModel):
    name: str = Field(..., title='Name')
    form: dict[str, Any] = Field(..., title='Form')
    data: dict[str, Any] | None = Field(None, title='Data')
    context: RecordContext
    auto_number: bool | None = Field(False, title='Auto Number')
    read_only: bool | None = Field(None, title='Read Only')


class RecordDuplicateBatch(BaseModel):
    source_ku_id: str = Field(..., title='Source Ku Id')
    source_kt_id: str = Field(..., title='Source Kt Id')
    source_product_id: str | None = Field(..., title='Source Product Id')
    target_ku_id: str = Field(..., title='Target Ku Id')
    target_kt_id: str = Field(..., title='Target Kt Id')
    target_product_id: str | None = Field(..., title='Target Product Id')


class RecordDuplicateBatchResponse(BaseModel):
    success: bool = Field(..., title='Success')
    message: str = Field(..., title='Message')


class TenantMetadata(BaseModel):
    tenant_id: str = Field(..., title='Tenant Id')


class UpdateRecordContext(BaseModel):
    linked_product: str | None = Field(None, title='Linked Product')
    linked_sop: str | None = Field(None, title='Linked Sop')
    linked_document: LinkedDocument | None = None
    group_id: str | None = Field(None, title='Group Id')


class ValidationError(BaseModel):
    loc: list[str | int] = Field(..., title='Location')
    msg: str = Field(..., title='Message')
    type: str = Field(..., title='Error Type')


class AuditInfo(BaseModel):
    user_id_created: str = Field(..., title='User Id Created')
    timestamp_created: datetime = Field(..., title='Timestamp Created')
    user_id_last_updated: str | None = Field(None, title='User Id Last Updated')
    timestamp_last_updated: datetime | None = Field(
        None, title='Timestamp Last Updated'
    )
    last_action: LastActionType


class GlobalElement(BaseModel):
    field_id: constr(pattern=r'^[0-9a-f]{24}$', min_length=24, max_length=24) | None = (
        Field(None, alias='_id', description='MongoDB document ObjectID')
    )
    name: str = Field(..., title='Name')
    schema_: dict[str, Any] | None = Field(None, alias='schema', title='Schema')
    description: str | None = Field(None, title='Description')
    metadata: TenantMetadata
    audit_info: AuditInfo
    type: GlobalElementType


class GlobalElementBulkRequest(BaseModel):
    ids: list[constr(pattern=r'^[0-9a-f]{24}$', min_length=24, max_length=24)] = Field(
        ..., title='Ids'
    )
    include_schema: bool | None = Field(True, title='Include Schema')


class GlobalElementBulkResponse(BaseModel):
    field_id: constr(pattern=r'^[0-9a-f]{24}$', min_length=24, max_length=24) | None = (
        Field(None, alias='_id')
    )
    name: str = Field(..., title='Name')
    schema_: dict[str, Any] | None = Field(None, alias='schema', title='Schema')
    description: str | None = Field(None, title='Description')
    metadata: TenantMetadata
    audit_info: AuditInfo
    type: GlobalElementType


class GlobalElementCreate(BaseModel):
    name: str = Field(..., title='Name')
    schema_: dict[str, Any] | None = Field(None, alias='schema', title='Schema')
    description: str | None = Field(None, title='Description')
    type: GlobalElementType


class GridFilterModel(BaseModel):
    items: list[GridFilterItem] = Field(..., title='Items')
    logicOperator: GridLogicOperator


class GridSettings(BaseModel):
    gridFilterModel: GridFilterModel | None = None
    columnVisibility: list[GridColumnVisibility] | None = Field(
        None, title='Columnvisibility'
    )
    gridDensity: GridDensity | None = None
    sorting: list[GridSorting] | None = Field(None, title='Sorting')


class HTTPValidationError(BaseModel):
    detail: list[ValidationError] | None = Field(None, title='Detail')


class QmList(BaseModel):
    field_id: constr(pattern=r'^[0-9a-f]{24}$', min_length=24, max_length=24) | None = (
        Field(None, alias='_id', description='MongoDB document ObjectID')
    )
    name: str = Field(..., title='Name')
    description: str | None = Field('', title='Description')
    metadata: TenantMetadata
    settings: GridSettings | None = None
    audit_info: AuditInfo
    category: Category | dict[str, Any] | None = Field(None, title='Category')
    filter_tag: str | None = Field(None, title='Filter Tag')
    template_ids: list[str] = Field(..., title='Template Ids')


class QmListCategory(BaseModel):
    field_id: constr(pattern=r'^[0-9a-f]{24}$', min_length=24, max_length=24) | None = (
        Field(None, alias='_id', description='MongoDB document ObjectID')
    )
    name: str = Field(..., title='Name')
    metadata: TenantMetadata
    audit_info: AuditInfo


class QmListUpdate(BaseModel):
    name: str | None = Field(None, title='Name')
    description: str | None = Field(None, title='Description')
    settings: GridSettings | None = None


class Record(BaseModel):
    field_id: constr(pattern=r'^[0-9a-f]{24}$', min_length=24, max_length=24) | None = (
        Field(None, alias='_id', description='MongoDB document ObjectID')
    )
    name: str = Field(..., title='Name')
    form: dict[str, Any] = Field(..., title='Form')
    version: str = Field(..., title='Version')
    data: dict[str, Any] = Field(..., title='Data')
    read_only: bool | None = Field(False, title='Read Only')
    metadata: TenantMetadata
    context: RecordContext | None
    audit_info: AuditInfo


class RecordBulkFetchByContextsResponse(RootModel[dict[str, list[Record]]]):
    root: dict[str, list[Record]]


class RecordUpdate(BaseModel):
    name: str | None = Field(None, title='Name')
    form: dict[str, Any] | None = Field(None, title='Form')
    data: dict[str, Any] | None = Field(None, title='Data')
    context: UpdateRecordContext | None = None
    read_only: bool | None = Field(None, title='Read Only')
