# generated by datamodel-codegen:
#   filename:  techdoc.json
#   timestamp: 2026-08-20T08:57:17+00:00

from __future__ import annotations

from datetime import datetime
from enum import StrEnum
from typing import Any, Literal

from pydantic import BaseModel, Field


class CreateKnowledgeTopicFromExisting(BaseModel):
    kt_schema_id: str | None = Field(
        None,
        description='ID of existing knowledge topic schema to copy from',
        title='Kt Schema Id',
    )
    kt_id: str | None = Field(
        None, description='ID of knowledge topic to create schema from', title='Kt Id'
    )
    include_content: bool | None = Field(
        False,
        description='Whether to include content in the copy',
        title='Include Content',
    )


class ExternalSourceInfo(BaseModel):
    is_external: Literal['true'] = Field(..., title='Is External')
    external_source_type: str = Field(..., title='External Source Type')
    external_source_id: str = Field(..., title='External Source Id')
    metadata: dict[str, Any] | None = Field(None, title='Metadata')


class IssuingEntityTypeEnum(StrEnum):
    EUDAMED = 'EUDAMED'
    GS1 = 'GS1'
    IFA = 'IFA'
    HIBCC = 'HIBCC'
    ICCBBA = 'ICCBBA'


class KnowledgeTopicType(StrEnum):
    single_record = 'single_record'
    multi_record = 'multi_record'
    product_data_collection = 'product_data_collection'


class KnowledgeTopicUpdate(BaseModel):
    data: dict[str, Any] | None = Field(None, title='Data')
    knowledge_topic_name: str | None = Field(None, title='Knowledge Topic Name')
    knowledge_topic_schema: dict[str, Any] | None = Field(
        None, title='Knowledge Topic Schema'
    )


class KnowledgeUnitRevisionSummary(BaseModel):
    id: str = Field(..., examples=['5eb7cf5a86d9755df3a6c593'], title='Id')
    name: str = Field(..., title='Name')
    version_string: str = Field(..., title='Version String')
    is_latest_approved: bool = Field(..., title='Is Latest Approved')
    read_only: bool = Field(..., title='Read Only')
    created_at: datetime = Field(..., title='Created At')
    updated_at: datetime | None = Field(None, title='Updated At')
    created_by: str = Field(..., title='Created By')
    updated_by: str | None = Field(None, title='Updated By')
    commit_message: str | None = Field(None, title='Commit Message')
    direct_approval_published_at: datetime | None = Field(
        None, title='Direct Approval Published At'
    )
    direct_approval_published_by: str | None = Field(
        None, title='Direct Approval Published By'
    )


class LastActionType(StrEnum):
    created = 'created'
    updated = 'updated'
    published = 'published'


class NoExternalSource(BaseModel):
    is_external: Literal['false'] = Field('false', title='Is External')


class OrderedKnowledgeTopic(BaseModel):
    knowledge_topic_id: str = Field(
        ..., examples=['5eb7cf5a86d9755df3a6c593'], title='Knowledge Topic Id'
    )
    index: int = Field(..., title='Index')


class ParentEntity(StrEnum):
    PRODUCT = 'PRODUCT'
    PRODUCT_FAMILY = 'PRODUCT_FAMILY'


class ProductContextQuestion(BaseModel):
    question: str = Field(..., title='Question')
    answer: str = Field(..., title='Answer')


class Regulation(StrEnum):
    MDR = 'MDR'
    IVDR = 'IVDR'


class Reusable(StrEnum):
    Surgical_Reusable_Instrument = 'Surgical Reusable Instrument'
    Other = 'Other'
    Single_Use = 'Single Use'


class RiskClass(StrEnum):
    I = 'I'
    IIa = 'IIa'
    IIb = 'IIb'
    III = 'III'
    A = 'A'
    B = 'B'
    C = 'C'
    D = 'D'


class Software(StrEnum):
    NoSoftware = 'NoSoftware'
    Software_Only = 'Software Only'
    Embedded = 'Embedded'


class SoftwareClass(StrEnum):
    NoSoftware = 'NoSoftware'
    A = 'A'
    B = 'B'
    C = 'C'


class TenantMetadata(BaseModel):
    tenant_id: str = Field(..., title='Tenant Id')


class TraceInfo(BaseModel):
    source: str = Field(..., title='Source')
    target: str = Field(..., title='Target')
    relation_type: str = Field(..., title='Relation Type')


class UseCaseAvailableRelation(BaseModel):
    relation_name: str = Field(..., title='Relation Name')
    target_knowledge_topic: str = Field(..., title='Target Knowledge Topic')


class UseCaseColumnView(BaseModel):
    relation_name: str = Field(..., title='Relation Name')
    target_knowledge_topic_name: str = Field(..., title='Target Knowledge Topic Name')
    target_knowledge_topic_history_id: str | None = Field(
        None, title='Target Knowledge Topic History Id'
    )
    allow_multiple: bool | None = Field(False, title='Allow Multiple')
    additional_field: str | None = Field(None, title='Additional Field')
    bidirection: bool = Field(..., title='Bidirection')
    description: str | None = Field(None, title='Description')
    field: str | None = Field('', title='Field')
    additional_field_key: str | None = Field(None, title='Additional Field Key')


class UseCaseDuplicateTopic(BaseModel):
    name: str = Field(..., title='Name')
    count: int = Field(..., title='Count')


class Status(StrEnum):
    complete = 'complete'
    incomplete = 'incomplete'
    duplicate = 'duplicate'


class UseCaseStatusView(BaseModel):
    use_case_name: str = Field(..., title='Use Case Name')
    status: Status = Field(..., title='Status')
    missing_topics: list[str] | None = Field([], title='Missing Topics')
    duplicate_topics: list[UseCaseDuplicateTopic] | None = Field(
        [], title='Duplicate Topics', validate_default=True
    )
    available_topics: list[str] | None = Field([], title='Available Topics')
    required_topics: list[str] | None = Field([], title='Required Topics')
    available_relations: list[UseCaseAvailableRelation] | None = Field(
        [], title='Available Relations', validate_default=True
    )
    is_valid: bool = Field(..., title='Is Valid')
    show_banner: bool = Field(..., title='Show Banner')


class ValidationError(BaseModel):
    loc: list[str | int] = Field(..., title='Location')
    msg: str = Field(..., title='Message')
    type: str = Field(..., title='Error Type')
    input: Any | None = Field(None, title='Input')
    ctx: dict[str, Any] | None = Field(None, title='Context')


class AuditInfo(BaseModel):
    user_id_created: str = Field(..., title='User Id Created')
    timestamp_created: datetime = Field(..., title='Timestamp Created')
    user_id_last_updated: str | None = Field(None, title='User Id Last Updated')
    timestamp_last_updated: datetime | None = Field(
        None, title='Timestamp Last Updated'
    )
    last_action: LastActionType
    direct_approval_published_at: datetime | None = Field(
        None, title='Direct Approval Published At'
    )
    direct_approval_published_by: str | None = Field(
        None, title='Direct Approval Published By'
    )


class CreateKnowledgeBase(BaseModel):
    knowledge_unit_name: str = Field(..., title='Knowledge Unit Name')
    is_not_editable_for_children: bool | None = Field(
        False, title='Is Not Editable For Children'
    )
    parent_entity: ParentEntity


class CreateKnowledgeTopic(BaseModel):
    knowledge_topic_name: str = Field(..., title='Knowledge Topic Name')
    knowledge_topic_schema: dict[str, Any] = Field(..., title='Knowledge Topic Schema')
    related_form_id: str = Field(..., title='Related Form Id')
    type: KnowledgeTopicType
    product_data_collection_id: str | None = Field(
        None, title='Product Data Collection Id'
    )
    external_source: NoExternalSource | ExternalSourceInfo | None = Field(
        None, title='External Source'
    )
    from_existing: CreateKnowledgeTopicFromExisting | None = None


class HTTPValidationError(BaseModel):
    detail: list[ValidationError] | None = Field(None, title='Detail')


class KnowledgeTopic(BaseModel):
    field_id: str | None = Field(
        None, alias='_id', description='MongoDB document ObjectID', title='Id'
    )
    knowledge_topic_name: str = Field(..., title='Knowledge Topic Name')
    type: KnowledgeTopicType
    knowledge_topic_history_id: str | None = Field(
        None, examples=['5eb7cf5a86d9755df3a6c593'], title='Knowledge Topic History Id'
    )
    product_history_id: str = Field(
        ..., examples=['5eb7cf5a86d9755df3a6c593'], title='Product History Id'
    )
    product_version: str | None = Field('0.1', title='Product Version')
    knowledge_unit_history_id: str = Field(
        ..., examples=['5eb7cf5a86d9755df3a6c593'], title='Knowledge Unit History Id'
    )
    knowledge_unit_version: str = Field(..., title='Knowledge Unit Version')
    knowledge_topic_schema: dict[str, Any] = Field(..., title='Knowledge Topic Schema')
    source_schema_id: str | None = Field(None, title='Source Schema Id')
    data: dict[str, Any] | None = Field({}, title='Data')
    product_data_collection_id: str | None = Field(
        None, title='Product Data Collection Id'
    )
    external_source: NoExternalSource | ExternalSourceInfo | None = Field(
        None, title='External Source'
    )
    metadata: TenantMetadata
    audit_info: AuditInfo | None = None


class KnowledgeUnitHistoryGroup(BaseModel):
    knowledge_unit_history_id: str = Field(
        ..., examples=['5eb7cf5a86d9755df3a6c593'], title='Knowledge Unit History Id'
    )
    name: str = Field(..., title='Name')
    latest_revision: KnowledgeUnitRevisionSummary
    latest_approved: KnowledgeUnitRevisionSummary | None = None
    revisions: list[KnowledgeUnitRevisionSummary] | None = Field(
        None, title='Revisions'
    )
    total_revisions: int | None = Field(0, title='Total Revisions')
    related_product_name: str = Field(..., title='Related Product Name')
    parent_entity: ParentEntity
    product_history_id: str | None = Field(None, title='Product History Id')
    product_family_history_id: str | None = Field(
        None, title='Product Family History Id'
    )
    revision_at_product_version: KnowledgeUnitRevisionSummary | None = None


class KnowledgeUnitUpdate(BaseModel):
    knowledge_unit_name: str | None = Field(None, title='Knowledge Unit Name')
    knowledge_unit_description: str | None = Field(
        None, title='Knowledge Unit Description'
    )
    knowledge_topics: list[KnowledgeTopicUpdate] | None = Field(
        None, title='Knowledge Topics'
    )
    is_not_editable_for_children: bool | None = Field(
        False, title='Is Not Editable For Children'
    )
    parent_entity: str | None = Field(None, title='Parent Entity')
    external_source: NoExternalSource | ExternalSourceInfo | None = Field(
        None, title='External Source'
    )


class ProductProperties(BaseModel):
    regulation: Regulation
    risk_class: RiskClass
    sterile: bool | None = Field(None, title='Sterile')
    reusable: Reusable | None = None
    measurement: bool | None = Field(None, title='Measurement')
    active: bool | None = Field(None, title='Active')
    invasive: bool | None = Field(None, title='Invasive')
    implantable: bool | None = Field(None, title='Implantable')
    medicinal_product: bool | None = Field(None, title='Medicinal Product')
    software: Software | None = 'NoSoftware'
    software_class: SoftwareClass | None = 'NoSoftware'
    biocompatibility: bool | None = Field(None, title='Biocompatibility')
    clinical_evaluation: bool | None = Field(None, title='Clinical Evaluation')
    performance_evaluation: bool | None = Field(None, title='Performance Evaluation')
    reprocessing: bool | None = Field(None, title='Reprocessing')
    reagents: bool | None = Field(None, title='Reagents')


class UseCaseConfigView(BaseModel):
    columns: list[UseCaseColumnView] | None = Field(
        [], title='Columns', validate_default=True
    )
    status: list[UseCaseStatusView] | None = Field(
        [], title='Status', validate_default=True
    )


class BodyCreateKnowledgeUnitKuPost(BaseModel):
    knowledge_unit: CreateKnowledgeBase
    product_history_id: str = Field(
        ..., examples=['5eb7cf5a86d9755df3a6c593'], title='Product History Id'
    )


class BodyCreateNewKnowledgeTopicKtPost(BaseModel):
    knowledge_topic: CreateKnowledgeTopic
    knowledge_unit_history_id: str = Field(
        ..., examples=['5eb7cf5a86d9755df3a6c593'], title='Knowledge Unit History Id'
    )


class FullKnowledgeUnitView(BaseModel):
    knowledge_unit_name: str = Field(..., title='Knowledge Unit Name')
    knowledge_unit_description: str | None = Field(
        '', title='Knowledge Unit Description'
    )
    parent_entity: ParentEntity
    product_history_id: str = Field(
        ..., examples=['5eb7cf5a86d9755df3a6c593'], title='Product History Id'
    )
    product_version: str | None = Field('0.1', title='Product Version')
    source_schema_id: str | None = Field(None, title='Source Schema Id')
    knowledge_topics: list[KnowledgeTopic] | None = Field(
        [], title='Knowledge Topics', validate_default=True
    )
    ordered_knowledge_topics: list[OrderedKnowledgeTopic] | None = Field(
        None, title='Ordered Knowledge Topics'
    )
    is_not_editable_for_children: bool | None = Field(
        False, title='Is Not Editable For Children'
    )
    knowledge_unit_history_id: str = Field(
        ..., examples=['5eb7cf5a86d9755df3a6c593'], title='Knowledge Unit History Id'
    )
    major_version: int = Field(..., title='Major Version')
    minor_version: int = Field(..., title='Minor Version')
    is_latest_approved: bool = Field(..., title='Is Latest Approved')
    read_only: bool = Field(..., title='Read Only')
    commit_message: str | None = Field(None, title='Commit Message')
    metadata: TenantMetadata
    audit_info: AuditInfo | None = None
    id: str = Field(..., examples=['5eb7cf5a86d9755df3a6c593'], title='Id')


class FullProductFamilyView(BaseModel):
    field_id: str | None = Field(
        None, alias='_id', description='MongoDB document ObjectID', title='Id'
    )
    name: str = Field(..., title='Name')
    udi: str | None = Field(None, title='Udi')
    udi_issuer: IssuingEntityTypeEnum | None = None
    lot_number: str | None = Field(None, title='Lot Number')
    serial_number: str | None = Field(None, title='Serial Number')
    notified_body: str | None = Field(None, title='Notified Body')
    ce_certificate_number: str | None = Field(None, title='Ce Certificate Number')
    regulatory_status: str | None = Field(None, title='Regulatory Status')
    product_properties: ProductProperties
    knowledge_units: list[FullKnowledgeUnitView] | None = Field(
        [], title='Knowledge Units', validate_default=True
    )
    product_family_history_id: str = Field(
        ..., examples=['5eb7cf5a86d9755df3a6c593'], title='Product Family History Id'
    )
    major_version: int = Field(..., title='Major Version')
    minor_version: int = Field(..., title='Minor Version')
    is_latest_approved: bool = Field(..., title='Is Latest Approved')
    read_only: bool = Field(..., title='Read Only')
    commit_message: str | None = Field(None, title='Commit Message')
    metadata: TenantMetadata
    audit_info: AuditInfo


class FullProductView(BaseModel):
    field_id: str | None = Field(
        None, alias='_id', description='MongoDB document ObjectID', title='Id'
    )
    name: str = Field(..., title='Name')
    udi: str | None = Field(None, title='Udi')
    udi_issuer: IssuingEntityTypeEnum | None = None
    udi_di: str | None = Field('N/A', title='Udi Di')
    lot_number: str | None = Field(None, title='Lot Number')
    serial_number: str | None = Field(None, title='Serial Number')
    notified_body: str | None = Field(None, title='Notified Body')
    ce_certificate_number: str | None = Field(None, title='Ce Certificate Number')
    product_properties: ProductProperties
    regulatory_status: str | None = Field(None, title='Regulatory Status')
    product_context: list[ProductContextQuestion] | None = Field(
        None, title='Product Context'
    )
    product_website: str | None = Field(None, title='Product Website')
    product_families: list[FullProductFamilyView] | None = Field(
        [], title='Product Families', validate_default=True
    )
    knowledge_units: list[FullKnowledgeUnitView] | None = Field(
        [], title='Knowledge Units', validate_default=True
    )
    product_history_id: str = Field(
        ..., examples=['5eb7cf5a86d9755df3a6c593'], title='Product History Id'
    )
    major_version: int = Field(..., title='Major Version')
    minor_version: int = Field(..., title='Minor Version')
    is_latest_approved: bool = Field(..., title='Is Latest Approved')
    read_only: bool = Field(..., title='Read Only')
    commit_message: str | None = Field(None, title='Commit Message')
    metadata: TenantMetadata
    audit_info: AuditInfo


class KnowledgeTopicDetailResponse(BaseModel):
    field_id: str = Field(
        ..., alias='_id', examples=['5eb7cf5a86d9755df3a6c593'], title='Id'
    )
    knowledge_topic_name: str = Field(..., title='Knowledge Topic Name')
    type: KnowledgeTopicType
    knowledge_topic_history_id: str = Field(
        ..., examples=['5eb7cf5a86d9755df3a6c593'], title='Knowledge Topic History Id'
    )
    product_history_id: str = Field(
        ..., examples=['5eb7cf5a86d9755df3a6c593'], title='Product History Id'
    )
    product_version: str = Field(..., title='Product Version')
    knowledge_unit_history_id: str = Field(
        ..., examples=['5eb7cf5a86d9755df3a6c593'], title='Knowledge Unit History Id'
    )
    knowledge_unit_version: str = Field(..., title='Knowledge Unit Version')
    knowledge_topic_schema: dict[str, Any] = Field(..., title='Knowledge Topic Schema')
    source_schema_id: str | None = Field(None, title='Source Schema Id')
    data: dict[str, Any] | None = Field({}, title='Data')
    product_data_collection_id: str | None = Field(
        None, title='Product Data Collection Id'
    )
    metadata: TenantMetadata
    audit_info: AuditInfo | None = None
    latest_revision_id: str | None = Field(None, title='Latest Revision Id')
    latest_or_latest_approved_revision_id: str | None = Field(
        None, title='Latest Or Latest Approved Revision Id'
    )
    use_case_config: UseCaseConfigView | None = None


class KnowledgeTopicWithTraces(BaseModel):
    field_id: str = Field(
        ..., alias='_id', examples=['5eb7cf5a86d9755df3a6c593'], title='Id'
    )
    knowledge_topic_name: str = Field(..., title='Knowledge Topic Name')
    type: KnowledgeTopicType
    knowledge_topic_history_id: str = Field(
        ..., examples=['5eb7cf5a86d9755df3a6c593'], title='Knowledge Topic History Id'
    )
    product_history_id: str = Field(
        ..., examples=['5eb7cf5a86d9755df3a6c593'], title='Product History Id'
    )
    product_version: str = Field(..., title='Product Version')
    knowledge_unit_history_id: str = Field(
        ..., examples=['5eb7cf5a86d9755df3a6c593'], title='Knowledge Unit History Id'
    )
    knowledge_unit_version: str = Field(..., title='Knowledge Unit Version')
    knowledge_topic_schema: dict[str, Any] = Field(..., title='Knowledge Topic Schema')
    source_schema_id: str | None = Field(None, title='Source Schema Id')
    data: dict[str, Any] | None = Field({}, title='Data')
    product_data_collection_id: str | None = Field(
        None, title='Product Data Collection Id'
    )
    metadata: TenantMetadata
    audit_info: AuditInfo | None = None
    latest_revision_id: str | None = Field(None, title='Latest Revision Id')
    latest_or_latest_approved_revision_id: str | None = Field(
        None, title='Latest Or Latest Approved Revision Id'
    )
    use_case_config: UseCaseConfigView | None = None
    external_source: NoExternalSource | ExternalSourceInfo | None = Field(
        None, title='External Source'
    )
    traces: list[TraceInfo] | None = Field([], title='Traces', validate_default=True)


class ProductCollection(BaseModel):
    products: list[FullProductView] = Field(..., title='Products')
