"""Generate outbound CertHub result payload and Sphinx summary RST."""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path

from certhub_connector.config.paths import certhub_result_path, git_head_commit, sphinx_generated_dir
from certhub_connector.evidence.verify import (
    ReqStatus,
    VerificationReport,
    format_verification_report,
    verify_certification,
)


def build_outbound_payload(report: VerificationReport) -> dict:
    req_payload = []
    for verdict in report.requirements:
        status_map = {
            ReqStatus.VERIFIED: "verified",
            ReqStatus.FAILED: "failed",
            ReqStatus.NOT_IMPLEMENTED: "not_implemented",
            ReqStatus.NOT_TESTED: "not_tested",
            ReqStatus.MISSING_DOUT: "missing_dout",
        }
        tests = []
        if verdict.verification:
            for tid in [part.strip() for part in verdict.verification.split(",")]:
                tests.append(
                    {
                        "id": tid,
                        "result": (verdict.result or "unknown").lower(),
                    }
                )
        req_payload.append(
            {
                "id": verdict.requirement_id,
                "status": status_map[verdict.status],
                "specification": verdict.specification,
                "implementation": verdict.implementation,
                "tests": tests,
            }
        )

    return {
        "project": report.project_id,
        "version": report.project_version,
        "commit": git_head_commit(),
        "generatedAt": datetime.now(timezone.utc).isoformat(),
        "certificationStatus": report.certification_status.value,
        "totals": report.totals,
        "requirements": req_payload,
    }


def write_certification_summary_rst(report: VerificationReport) -> Path:
    docs_dir = sphinx_generated_dir()
    docs_dir.mkdir(parents=True, exist_ok=True)
    path = docs_dir / "certification_summary.rst"
    status = report.certification_status.value
    t = report.totals
    rows = []
    for v in report.requirements:
        rows.append(
            f"   * - {v.requirement_id}\n"
            f"     - {v.status.value}\n"
            f"     - {v.specification or 'MISSING'}\n"
            f"     - {v.implementation or 'MISSING'}\n"
            f"     - {v.verification or 'MISSING'}\n"
            f"     - {v.result or 'N/A'}"
        )
    table = "\n".join(rows)
    blocked_note = ""
    if status == "BLOCKED":
        blocked_note = (
            "\n.. admonition:: Gate BLOCKED\n"
            "   :class: danger\n"
            "\n"
            "   Certification is blocked for this build. "
            "See :doc:`verification` and :doc:`traceability` for gaps.\n"
        )
    content = f""".. GENERATED by cadence report — DO NOT EDIT BY HAND

**Certification status: {status}**
{blocked_note}
* System Requirements: {t['system_requirements']}
* Design Outputs: {t['design_outputs']}
* Verifications: {t['verifications']}
* Validations: {t['validations']}
* Implemented: {t['implemented']} / {t['system_requirements']}
* Verified: {t['verified']} / {t['system_requirements']}
* Passed tests: {t['passed']}
* Failed tests: {t['failed']}

.. list-table:: Per-requirement chain (SYSREQ → DOUT → code → VERIF → result)
   :header-rows: 1
   :widths: 12 14 12 28 14 12

   * - Requirement
     - Status
     - Design Output
     - Implementation (code)
     - Verification
     - Result
{table}
"""
    path.write_text(content, encoding="utf-8")
    return path


def generate_report(report: VerificationReport | None = None) -> tuple[Path, Path, str]:
    report = report or verify_certification()
    out = certhub_result_path()
    out.parent.mkdir(parents=True, exist_ok=True)
    payload = build_outbound_payload(report)
    out.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    summary = write_certification_summary_rst(report)
    text = format_verification_report(report)
    return out, summary, text
